/*
     http://www.apache.org/licenses/LICENSE-2.0.html Apache 2 License
*/
(function(c){c.widget("neatline.bubbles",{_create:function(){this._body=c("body");this._window=c(window);this.template=_.template(c("#bubble-template").html());this.opacity=this.background=this.body=this.title=this.bubble=null;this.onBubble=this.frozen=!1;this._window.bind("mouseleave",_.bind(function(){this.hide()},this))},show:function(a,d){if(!this.frozen&&!(a==""&&d==""))this.title=a,this.body=d,_.isNull(this.bubble)||this.bubble.remove(),this.bubble=c(this.template({title:a,body:d})),this.freezeLink=
this.bubble.find("a.freeze-bubble"),this.closeLink=this.bubble.find("a.close-bubble"),this.moreInfoDiv=this.bubble.find("div.click-for-info"),this.titleDiv=this.bubble.find("div.title"),this.bodyDiv=this.bubble.find("div.body"),this.body===""&&(this.moreInfoDiv.hide(),this.bubble.addClass("no-body")),this._measureBubble(),this.element.append(this.bubble),this.background=this.bubble.css("background-color"),this.opacity=this.bubble.css("opacity"),this._window.bind({"mousemove.bubbles":_.bind(function(a){this.position(a)},
this)})},close:function(){this._trigger("close");this.frozen=!1;this.hide()},hide:function(){if(!this.frozen&&!_.isNull(this.bubble))this.bubble.remove(),this.bubble=null,this._window.unbind("mousemove.bubbles mousedown.bubbles")},freeze:function(){if(!_.isNull(this.bubble))this.frozen=!0,this._window.unbind("mousemove.bubbles"),this.bubble.addClass("frozen"),this.opacity=this.bubble.css("opacity"),this._measureBubble(),this.position(this.event),this.bubble.bind({mouseenter:_.bind(function(){this.onBubble=
!0},this),mouseleave:_.bind(function(){this.onBubble=!1},this)}),this._window.bind("mousedown.bubbles",_.bind(function(){this.onBubble||this.close()},this)),this.closeLink.mousedown(_.bind(function(){this.close()},this))},position:function(a){this.event=a;var d=this.element.outerWidth(),c=this.element.outerHeight(),b=this.element.offset(),e=parseInt(this.element.css("border-top-width"),10),f=parseInt(this.element.css("border-left-width"),10);b.top+=e;b.left+=f;e=a.clientX-b.left;f=a.clientY-b.top+
this._window.scrollTop();if(a.clientX<b.left||a.clientX>b.left+d||a.clientY<b.top||a.clientY>b.top+c)this._trigger("cursorleave"),this.hide();else{a=f-this.bubbleHeight/3;b=e+20;b+this.bubbleWidth>d&&(b=e-this.bubbleWidth-20);a<0&&(a=0);a+this.bubbleHeight>c&&(a=c-this.bubbleHeight);if(this.bubbleHeight>c)a=0,this.bubbleHeight=c,this.bubble.css("overflow-y","scroll"),this.bubble.outerHeight(this.bubbleHeight);this.bubble.css({left:b,top:a})}},_measureBubble:function(){var a=this.bubble.clone().css({top:-1E3,
left:-1E3}).appendTo(this._body);this.bubbleHeight=a.outerHeight();this.bubbleWidth=a.outerWidth();a.remove()},getTitle:function(){return this.title},isFrozen:function(){return this.frozen}})})(jQuery);
