/*
     http://www.apache.org/licenses/LICENSE-2.0.html Apache 2 License
*/
(function(b){b.widget("neatline.positioner",{options:{draggable:!0,mapFullscreen:!0,colors:{drag_active:"#1e1e1e"},markup:{map:"#map",timeline:"#timeline",items:"#items"},constants:{h_percent:24,v_percent:84,drag_width:5},positions:{is_map:!1,is_timeline:!1,is_items:!1,top:"map",items_v_pos:"bottom",items_h_pos:"right",items_height:"full"}},_create:function(){this._window=b(window);this.map=b(this.options.markup.map);this.timeline=b(this.options.markup.timeline);this.items=b(this.options.markup.items);
this._is_map=this.options.positions.is_map;this._is_timeline=this.options.positions.is_timeline;this._is_items=this.options.positions.is_items;this._top=this.options.positions.top;this._items_v_pos=this.options.positions.items_v_pos;this._items_h_pos=this.options.positions.items_h_pos;this._items_height=this.options.positions.items_height;this.h_drag=this.v_drag=null;this.positions={map:{height:null,width:null,top:null,left:null},timeline:{height:null,width:null,top:null,left:null},items:{height:null,
width:null,top:null,left:null}};this.options.draggable&&this._constructDraggers();this.measure()},measure:function(){this.width=this.element.width();this.height=this.element.height();this.minorWidth=this.width*(this.options.constants.h_percent/100);this.majorWidth=this.width-this.minorWidth;this.majorHeight=this.height*(this.options.constants.v_percent/100);this.minorHeight=this.height-this.majorHeight},compute:function(a,b,d,e,c,f,g){this._is_map=a;this._is_timeline=b;this._is_items=d;this._top=
e;this._items_v_pos=c;this._items_h_pos=f;this._items_height=g;if(this._is_map&&this._is_timeline&&this._is_items)if(this._top==="map"){if(this._items_h_pos==="left"&&this._items_v_pos==="bottom"&&this._items_height==="partial")this.positions={map:{height:this.majorHeight,width:this.width,top:0,left:0},timeline:{height:this.minorHeight,width:this.majorWidth,top:this.majorHeight,left:this.minorWidth},items:{height:this.minorHeight,width:this.minorWidth,top:this.majorHeight,left:0}},this.dragPositions=
{h:{height:this.minorHeight,width:this.options.constants.drag_width,top:this.majorHeight,left:this.minorWidth},v:{height:this.options.constants.drag_width,width:this.width,top:this.majorHeight,left:0}};if(this._items_h_pos==="left"&&this._items_v_pos==="top"&&this._items_height==="partial")this.positions={map:{height:this.majorHeight,width:this.majorWidth,top:0,left:this.minorWidth},timeline:{height:this.minorHeight,width:this.width,top:this.majorHeight,left:0},items:{height:this.majorHeight,width:this.minorWidth,
top:0,left:0}},this.dragPositions={h:{height:this.majorHeight,width:this.options.constants.drag_width,top:0,left:this.minorWidth},v:{height:this.options.constants.drag_width,width:this.width,top:this.majorHeight,left:0}};else if(this._items_h_pos==="left"&&this._items_height==="full")this.positions={map:{height:this.majorHeight,width:this.majorWidth,top:0,left:this.minorWidth},timeline:{height:this.minorHeight,width:this.majorWidth,top:this.majorHeight,left:this.minorWidth},items:{height:this.height,
width:this.minorWidth,top:0,left:0}},this.dragPositions={h:{height:this.height,width:this.options.constants.drag_width,top:0,left:this.minorWidth},v:{height:this.options.constants.drag_width,width:this.majorWidth,top:this.majorHeight,left:this.minorWidth}};if(this._items_h_pos==="right"&&this._items_v_pos==="bottom"&&this._items_height==="partial")this.positions={map:{height:this.majorHeight,width:this.width,top:0,left:0},timeline:{height:this.minorHeight,width:this.majorWidth,top:this.majorHeight,
left:0},items:{height:this.minorHeight,width:this.minorWidth,top:this.majorHeight,left:this.majorWidth}},this.dragPositions={h:{height:this.minorHeight,width:this.options.constants.drag_width,top:this.majorHeight,left:this.majorWidth},v:{height:this.options.constants.drag_width,width:this.width,top:this.majorHeight,left:0}};if(this._items_h_pos==="right"&&this._items_v_pos==="top"&&this._items_height==="partial")this.positions={map:{height:this.majorHeight,width:this.majorWidth,top:0,left:0},timeline:{height:this.minorHeight,
width:this.width,top:this.majorHeight,left:0},items:{height:this.majorHeight,width:this.minorWidth,top:0,left:this.majorWidth}},this.dragPositions={h:{height:this.majorHeight,width:this.options.constants.drag_width,top:0,left:this.majorWidth},v:{height:this.options.constants.drag_width,width:this.width,top:this.majorHeight,left:0}};else if(this._items_h_pos==="right"&&this._items_height==="full")this.positions={map:{height:this.majorHeight,width:this.majorWidth,top:0,left:0},timeline:{height:this.minorHeight,
width:this.majorWidth,top:this.majorHeight,left:0},items:{height:this.height,width:this.minorWidth,top:0,left:this.majorWidth}},this.dragPositions={h:{height:this.height,width:this.options.constants.drag_width,top:0,left:this.majorWidth},v:{height:this.options.constants.drag_width,width:this.majorWidth,top:this.majorHeight,left:0}}}else{if(this._top==="timeline"){if(this._items_h_pos==="left"&&this._items_v_pos==="bottom"&&this._items_height==="partial")this.positions={map:{height:this.minorHeight,
width:this.majorWidth,top:this.majorHeight,left:this.minorWidth},timeline:{height:this.majorHeight,width:this.width,top:0,left:0},items:{height:this.minorHeight,width:this.minorWidth,top:this.majorHeight,left:0}},this.dragPositions={h:{height:this.minorHeight,width:this.options.constants.drag_width,top:this.majorHeight,left:this.minorWidth},v:{height:this.options.constants.drag_width,width:this.width,top:this.majorHeight,left:0}};if(this._items_h_pos==="left"&&this._items_v_pos==="top"&&this._items_height===
"partial")this.positions={map:{height:this.minorHeight,width:this.width,top:this.majorHeight,left:0},timeline:{height:this.majorHeight,width:this.majorWidth,top:0,left:this.minorWidth},items:{height:this.majorHeight,width:this.minorWidth,top:0,left:0}},this.dragPositions={h:{height:this.majorHeight,width:this.options.constants.drag_width,top:0,left:this.minorWidth},v:{height:this.options.constants.drag_width,width:this.width,top:this.majorHeight,left:0}};else if(this._items_h_pos==="left"&&this._items_height===
"full")this.positions={map:{height:this.minorHeight,width:this.majorWidth,top:this.majorHeight,left:this.minorWidth},timeline:{height:this.majorHeight,width:this.majorWidth,top:0,left:this.minorWidth},items:{height:this.height,width:this.minorWidth,top:0,left:0}},this.dragPositions={h:{height:this.height,width:this.options.constants.drag_width,top:0,left:this.minorWidth},v:{height:this.options.constants.drag_width,width:this.majorWidth,top:this.majorHeight,left:this.minorWidth}};if(this._items_h_pos===
"right"&&this._items_v_pos==="bottom"&&this._items_height==="partial")this.positions={map:{height:this.minorHeight,width:this.majorWidth,top:this.majorHeight,left:0},timeline:{height:this.majorHeight,width:this.width,top:0,left:0},items:{height:this.minorHeight,width:this.minorWidth,top:this.majorHeight,left:this.majorWidth}},this.dragPositions={h:{height:this.minorHeight,width:this.options.constants.drag_width,top:this.majorHeight,left:this.majorWidth},v:{height:this.options.constants.drag_width,
width:this.width,top:this.majorHeight,left:0}};if(this._items_h_pos==="right"&&this._items_v_pos==="top"&&this._items_height==="partial")this.positions={map:{height:this.minorHeight,width:this.width,top:this.majorHeight,left:0},timeline:{height:this.majorHeight,width:this.majorWidth,top:0,left:0},items:{height:this.majorHeight,width:this.minorWidth,top:0,left:this.majorWidth}},this.dragPositions={h:{height:this.majorHeight,width:this.options.constants.drag_width,top:0,left:this.majorWidth},v:{height:this.options.constants.drag_width,
width:this.width,top:this.majorHeight,left:0}};else if(this._items_h_pos==="right"&&this._items_height==="full")this.positions={map:{height:this.minorHeight,width:this.majorWidth,top:this.majorHeight,left:0},timeline:{height:this.majorHeight,width:this.majorWidth,top:0,left:0},items:{height:this.height,width:this.minorWidth,top:0,left:this.majorWidth}},this.dragPositions={h:{height:this.height,width:this.options.constants.drag_width,top:0,left:this.majorWidth},v:{height:this.options.constants.drag_width,
width:this.majorWidth,top:this.majorHeight,left:0}}}}else if(this._is_map&&this._is_items&&!this._is_timeline)if(this._items_h_pos==="right")this.positions={map:{height:this.height,width:this.majorWidth,top:0,left:0},timeline:{height:null,width:null,top:null,left:null},items:{height:this.height,width:this.minorWidth,top:0,left:this.majorWidth}},this.dragPositions={h:{height:this.height,width:this.options.constants.drag_width,top:0,left:this.majorWidth},v:{height:null,width:null,top:null,left:null}};
else{if(this._items_h_pos==="left")this.positions={map:{height:this.height,width:this.majorWidth,top:0,left:this.minorWidth},timeline:{height:null,width:null,top:null,left:null},items:{height:this.height,width:this.minorWidth,top:0,left:0}},this.dragPositions={h:{height:this.height,width:this.options.constants.drag_width,top:0,left:this.majorWidth},v:{height:null,width:null,top:null,left:null}}}else if(this._is_timeline&&this._is_items&&!this._is_map)if(this._items_h_pos==="right")this.positions=
{map:{height:null,width:null,top:null,left:null},timeline:{height:this.height,width:this.majorWidth,top:0,left:0},items:{height:this.height,width:this.minorWidth,top:0,left:this.majorWidth}},this.dragPositions={h:{height:this.height,width:this.options.constants.drag_width,top:0,left:this.majorWidth},v:{height:null,width:null,top:null,left:null}};else{if(this._items_h_pos==="left")this.positions={map:{height:null,width:null,top:null,left:null},timeline:{height:this.height,width:this.majorWidth,top:0,
left:this.minorWidth},items:{height:this.height,width:this.minorWidth,top:0,left:0}},this.dragPositions={h:{height:this.height,width:this.options.constants.drag_width,top:0,left:this.majorWidth},v:{height:null,width:null,top:null,left:null}}}else if(this._is_map&&this._is_timeline&&!this._is_items)if(this._top==="map")this.positions={map:{height:this.majorHeight,width:this.width,top:0,left:0},timeline:{height:this.minorHeight,width:this.width,top:this.majorHeight,left:0},items:{height:null,width:null,
top:null,left:null}},this.dragPositions={h:{height:null,width:null,top:null,left:null},v:{height:this.options.constants.drag_width,width:this.width,top:this.majorHeight,left:0}};else{if(this._top==="timeline")this.positions={map:{height:this.minorHeight,width:this.width,top:this.majorHeight,left:0},timeline:{height:this.majorHeight,width:this.width,top:0,left:0},items:{height:null,width:null,top:null,left:null}},this.dragPositions={h:{height:null,width:null,top:null,left:null},v:{height:this.options.constants.drag_width,
width:this.width,top:this.majorHeight,left:0}}}else if(this._is_map&&!this._is_timeline&&!this._is_items)this.positions={map:{height:this.height,width:this.width,top:0,left:0},timeline:{height:null,width:null,top:null,left:null},items:{height:null,width:null,top:null,left:null}},this.dragPositions={h:{height:null,width:null,top:null,left:null},v:{height:null,width:null,top:null,left:null}};else if(this._is_timeline&&!this._is_map&&!this._is_items)this.positions={map:{height:null,width:null,top:null,
left:null},timeline:{height:this.height,width:this.width,top:0,left:0},items:{height:null,width:null,top:null,left:null}},this.dragPositions={h:{height:null,width:null,top:null,left:null},v:{height:null,width:null,top:null,left:null}};this.options.draggable&&this._showDraggers();return this.positions},apply:function(){this._is_map?(this.map.css("display","block"),this.options.mapFullscreen?this.map.css({height:this.height,width:this.width,top:0,left:0}):this.map.css(this.positions.map)):this.map.css("display",
"none");this._is_timeline?(this.timeline.css("display","block"),this.timeline.css(this.positions.timeline)):this.timeline.css("display","none");this._is_items?(this.items.css("display","block"),this.items.css(this.positions.items)):this.items.css("display","none")},_constructDraggers:function(){var a=this;this.v_drag=b('<div class="v-drag">                              </div>');this.h_drag=b('<div class="h-drag">                              </div>');this.element.append(this.v_drag,this.h_drag);this.h_drag.bind({mousedown:function(b){var d=
b.pageX,e=a.dragPositions.h.left;a.__highlightHorizontalHandle();a.__disableSelection();a._window.bind({mousemove:function(c){var c=e-(d-c.pageX),b=a.width-a.options.constants.drag_width;c<0?c=0:c>b&&(c=b);a.h_drag.css("left",c);switch(a._items_h_pos){case "left":a.options.constants.h_percent=c/a.width*100;break;case "right":a.options.constants.h_percent=(a.width-c)/a.width*100}a._trigger("drag",{},{h_percent:a.options.constants.h_percent,v_percent:a.options.constants.v_percent});a.refresh()},mouseup:function(){a.refresh();
a.__unhighlightHorizontalHandle();a.__enableSelection();a._window.unbind("mousemove");a._trigger("layoutChange")}})}});this.v_drag.bind({mousedown:function(b){var d=b.pageY,e=a.dragPositions.v.top;a.__highlightVerticalHandle();a.__disableSelection();a._window.bind({mousemove:function(c){var c=e-(d-c.pageY),b=a.height-a.options.constants.drag_width;c<0?c=0:c>b&&(c=b);a.v_drag.css("top",c);a.options.constants.v_percent=c/a.height*100;a._trigger("drag",{},{h_percent:a.options.constants.h_percent,v_percent:a.options.constants.v_percent});
a.refresh()},mouseup:function(){a.refresh();a.__unhighlightVerticalHandle();a.__enableSelection();a._window.unbind("mousemove");a._window.unbind("mouseup");a._trigger("layoutChange")}})}})},_showDraggers:function(){this._is_map&&this._is_timeline?this.v_drag.css("display","block"):this.v_drag.css("display","none");this._is_items?this.h_drag.css("display","block"):this.h_drag.css("display","none");this.h_drag.css(this.dragPositions.h);this.v_drag.css(this.dragPositions.v)},applyProportions:function(a,
b){this.options.constants.h_percent=a;this.options.constants.v_percent=b;this.refresh()},refresh:function(){this.measure();this.compute(this._is_map,this._is_timeline,this._is_items,this._top,this._items_v_pos,this._items_h_pos,this._items_height);this.apply()},__highlightHorizontalHandle:function(){this.h_drag.css("border-left","1px dashed "+this.options.colors.drag_active)},__unhighlightHorizontalHandle:function(){this.h_drag.css("border-left","")},__highlightVerticalHandle:function(){this.v_drag.css("border-top",
"1px dashed "+this.options.colors.drag_active)},__unhighlightVerticalHandle:function(){this.v_drag.css("border-top","")},__disableSelection:function(){this.element.css({"-moz-user-select":"none","-khtml-user-select":"none","-webkit-user-select":"none","user-select":"none"})},__enableSelection:function(){this.element.css({"-moz-user-select":"","-khtml-user-select":"","-webkit-user-select":"","user-select":""})},getAttr:function(a){return this[a]}})})(jQuery);
