/*
     http://www.apache.org/licenses/LICENSE-2.0.html Apache 2 License
*/
jQuery(document).ready(function(e){SimileAjax.History.enabled=!1;var b=e("#neatline"),d=e("#item-browser"),g=e("#configure-layout-button"),h=e("#configure-map-button"),i=e("#configure-timeline-button"),f=e("#configure-items-button");d.itembrowser({neatlineready:function(){b.neatline({isPublic:!1,timelineeventclick:function(b,a){d.itembrowser("showFormByRecordId",a.recordid,!0,!1,!0)},mapfeatureclick:function(b,a){d.itembrowser("showFormByRecordId",a.recordid,!1,!0,!0)},itemclick:function(b,a){d.itembrowser("showFormByRecordId",
a.recordid,!0,!0,a.scrollItems)},mapfeatureadded:function(b,a){d.itembrowser("updateGeocoverage",a.geocoverage)},newitems:function(){var c=d.itembrowser("getCurrentEditId");c&&b.neatline("showItemDescription",c)},widthdrag:function(b,a){g.configurelayout("setViewportProportions",a.h_percent,a.v_percent)}});b.on({drawingmodeon:function(){var b=d.data("itembrowser");b.editForm!=null&&b.editForm.itemform("lockForm")},drawingmodeoff:function(){var b=d.data("itembrowser");b.editForm!=null&&b.editForm.itemform("unlockForm")}})},
reposition:function(){b.neatline("positionDivs");b.neatline("positionBlockMarkup")},mapedit:function(c,a){b.neatline("editMap",a.item,a.immediate)},endmapedit:function(c,a){b.neatline("endMapEditWithoutSave",a.immediate)},savecomplete:function(){b.neatline("reloadTimeline");b.neatline("reloadMap");b.neatline("reloadItems")},itemedit:function(c,a){a.scrollMap&&b.neatline("zoomMapToItemVectors",a.recordid);a.scrollTimeline&&b.neatline("zoomTimelineToEvent",a.recordid);a.focusItems&&b.neatline("showItemDescription",
a.recordid)},vectorcoloredit:function(c,a){b.neatline("setItemVectorColor",a.color,a.recordid)},strokecoloredit:function(c,a){b.neatline("setItemStrokeColor",a.color)},highlightcoloredit:function(c,a){b.neatline("setItemHighlightColor",a.color)},vectoropacityedit:function(c,a){b.neatline("setItemVectorOpacity",a.value)},strokeopacityedit:function(c,a){b.neatline("setItemStrokeOpacity",a.value)},graphicopacityedit:function(c,a){b.neatline("setItemGraphicOpacity",a.value)},strokewidthedit:function(c,
a){b.neatline("setItemStrokeWidth",a.value)},pointradiusedit:function(c,a){b.neatline("setItemPointRadius",a.value)},ambiguityChange:function(c,a){b.neatline("setDateAmbiguity",a.recordid,a.color,a.leftPercent,a.rightPercent)},savemapfocus:function(){var c=b.neatline("getMapCenter"),a=b.neatline("getMapZoom");d.itembrowser("saveMapFocus",c,a)},saveform:function(){var c=b.neatline("getWktForSave");d.itembrowser("saveForm",c)}});g.configurelayout({savepositions:function(){var c=b.neatline("getMapCenter"),
a=b.neatline("getMapZoom"),d=b.neatline("getMapBaseLayer"),e=b.neatline("getTimelineCenter"),f=b.neatline("getTimelineZoom");g.configurelayout("savePositions",c,a,d,e,f)},newarrangement:function(c,a){b.neatline("setParams",a.params);b.neatline("positionDivs");b.neatline("positionBlockMarkup");b.neatline("instantiateBlocks");b.neatline("saveSuccess")},newpositions:function(){b.neatline("saveSuccess")},widthDrag:function(c,a){b.neatline("applyViewportProportions",a.h_percent,a.v_percent)}});h.configuremap({vectorcoloredit:function(c,
a){b.neatline("setDefaultVectorColor",a.color)},strokecoloredit:function(c,a){b.neatline("setDefaultStrokeColor",a.color)},highlightcoloredit:function(c,a){b.neatline("setDefaultHighlightColor",a.color)},vectoropacityedit:function(c,a){b.neatline("setDefaultVectorOpacity",a.value)},strokeopacityedit:function(c,a){b.neatline("setDefaultStrokeOpacity",a.value)},graphicopacityedit:function(c,a){b.neatline("setItemGraphicOpacity",a.value)},strokewidthedit:function(c,a){b.neatline("setDefaultStrokeWidth",
a.value)},pointradiusedit:function(c,a){b.neatline("setDefaultPointRadius",a.value)},newdefaults:function(){b.neatline("saveSuccess");d.itembrowser("reloadItemForm")}});i.configuretimeline({newdefaults:function(c,a){b.neatline("saveSuccess");b.neatline("renderTimelineDefaults",a.context_band_height,a.context_band_unit,a.is_context_band)}});f.configureitems({reorder:function(){b.neatline("reorderItems")},getorder:function(){var c=b.neatline("getOrder");f.configureitems("setOrder",c)},endreorder:function(){var c=
b.neatline("endReorderItems");f.configureitems("setOrder",c)},neworder:function(){b.neatline("saveSuccess")}});var j=[g.data("configurelayout").element.data("nlDropdown"),h.data("configuremap").element.data("nlDropdown"),i.data("configuretimeline").element.data("nlDropdown"),f.data("configureitems").element.data("nlDropdown")];_.each(j,function(b){b.setRadioDropdowns(j)})});
