/*
     http://www.apache.org/licenses/LICENSE-2.0.html Apache 2 License
*/
(function(d){d.widget("neatline.itemform",{options:{css:{default_text_size:14,form_duration:300},colors:{light_blue:"#f3f6ff",light_yellow:"#fffef8",dark_purple:"#594e62",purple:"#724e85",text:"#515151",gray:"#8d8d8d",red:"#ca3c3c",orange:"#ffda82"},cleditor:{description:{width:340,height:300,controls:"bold italic underline | font size | color removeformat | bullets numbering | outdent indent | alignleft center alignright justify | rule image link unlink | source"},title:{width:340,height:100,controls:"bold italic underline | font size color | bullets outdent indent | source removeformat"}}},
_create:function(){this._window=d(window);this.item=this.element.prev("item-row");this.form=this.element.find("form");this.deleteButton=this.form.find("#record-delete-button");this.closeButton=this.form.find("#record-close-button");this.saveButton=this.form.find("#record-save-button");this.title=this.form.find('textarea[name="title"]');this.slug=this.form.find('input[name="slug"]');this.description=this.form.find('textarea[name="description"]');this.showBubble=this.form.find('input[name="show-bubble"]');
this.useDcData=this.form.find('input[name="use-dc-data"]');this.useDcDataLabel=this.useDcData.next("span");this.startDate=this.form.find('input[name="start-date-date"]');this.endDate=this.form.find('input[name="end-date-date"]');this.startVisibleDate=this.form.find('input[name="start-visible-date"]');this.endVisibleDate=this.form.find('input[name="end-visible-date"]');this.geocoverage=this.form.find('textarea[name="geocoverage"]');this.vectorColor=this.form.find('input[name="vector-color"]');this.strokeColor=
this.form.find('input[name="stroke-color"]');this.highlightColor=this.form.find('input[name="highlight-color"]');this.vectorOpacity=this.form.find('input[name="vector-opacity"]');this.selectOpacity=this.form.find('input[name="select-opacity"]');this.strokeOpacity=this.form.find('input[name="stroke-opacity"]');this.graphicOpacity=this.form.find('input[name="graphic-opacity"]');this.strokeWidth=this.form.find('input[name="stroke-width"]');this.pointRadius=this.form.find('input[name="point-radius"]');
this.pointImage=this.form.find('input[name="point-image"]');this.leftPercent=this.form.find('input[name="left-ambiguity-percentage"]');this.rightPercent=this.form.find('input[name="right-ambiguity-percentage"]');this.textInputs=this.form.find('input[type="text"], textarea');this.fieldset=this.form.find("fieldset");this.actions=this.form.find("#edit-form-actions");this.inputs=this.form.find("#edit-form-inputs");this.ambiguity=this.form.find(".date-ambiguity-container");this.mapFocus=this.form.find(".map-focus");
this.resetStyles=this.form.find(".reset-styles");this.parentRecord=this.form.find('select[name="parent-record"]');this.titleDescriptionFieldset=this.form.find("a.fieldset.text");this.dateInformationFieldset=this.form.find("a.fieldset.temporal");this.mapStylesFieldset=this.form.find("a.fieldset.styles");this.relationshipsFieldset=this.form.find("a.fieldset.relationships");this._db=TAFFY();this._isForm=!1;this.coverage=this._data=null;this._isLocked=!1;this._buildFormFunctionality();this._buildFieldsets();
this._measureForm()},_buildFormFunctionality:function(){var a=this;this.titleEditor=this.title.cleditor(this.options.cleditor.title)[0];this.descriptionEditor=this.description.cleditor(this.options.cleditor.description)[0];this.useDcData.bind("change",_.bind(function(){this.useDcData.prop("checked")?(this._disableTextEditors(),this._postDcDefaultStatus(!0)):(this._enableTextEditors(),this._postDcDefaultStatus(!1))},this));this.ambiguity.gradientbuilder({stopHandleDrag:function(b,c){a._trigger("ambiguityChange",
{},{itemId:c.itemId,color:c.color,leftPercent:c.leftPercent,rightPercent:c.rightPercent})}});this.vectorColor.miniColors({change:function(b){a._opened||a._trigger("formEdit");a._trigger("vectorColorEdit",{},{color:b});a.ambiguity.gradientbuilder("setColor",b)}});this.strokeColor.miniColors({change:function(b){a._trigger("strokeColorEdit",{},{color:b})}});this.highlightColor.miniColors({change:function(b){a._trigger("highlightColorEdit",{},{color:b})}});this.vectorOpacity.integerdragger({min:0,max:100,
px_per_unit:3,tip:{show:!1},change:function(b,c){a._trigger("vectorOpacityEdit",{},{value:c.value})}});this.selectOpacity.integerdragger({min:0,max:100,px_per_unit:3,tip:{show:!1},change:function(b,c){a._trigger("selectOpacityEdit",{},{value:c.value})}});this.strokeOpacity.integerdragger({min:0,max:100,px_per_unit:3,tip:{show:!1},change:function(b,c){a._trigger("strokeOpacityEdit",{},{value:c.value})}});this.graphicOpacity.integerdragger({min:0,max:100,px_per_unit:3,tip:{show:!1},change:function(b,
c){a._trigger("graphicOpacityEdit",{},{value:c.value})}});this.strokeWidth.integerdragger({min:0,def:1,px_per_unit:8,tip:{show:!1},change:function(b,c){a._trigger("strokeWidthEdit",{},{value:c.value})}});this.pointRadius.integerdragger({min:1,def:6,px_per_unit:8,tip:{show:!1},change:function(b,c){a._trigger("pointRadiusEdit",{},{value:c.value})}});this.saveButton.bind({mousedown:function(){a.saveItemForm()},click:function(a){a.preventDefault()}});this.closeButton.bind({mousedown:function(){a._trigger("hide")},
click:function(a){a.preventDefault()}});this.deleteButton.bind({mousedown:function(){_.isNumber(this.itemId)||(a._fadeDown(),a.postRecordDelete())},click:function(a){a.preventDefault()}});this.mapFocus.bind({mousedown:function(){a._fadeDown();a._trigger("savemapfocus")},click:function(a){a.preventDefault()}});this.resetStyles.bind({mousedown:function(){a._fadeDown();a.postResetStyles()},click:function(a){a.preventDefault()}});this.textInputs.bind("keydown",function(){a._trigger("formEdit")})},_buildFieldsets:function(){this.form.tabs()},
showForm:function(a){if(!this._isLocked){this.item=a;var b=a.attr("itemid"),c=a.attr("recordid");this.itemTitleText=a.find(".item-title-text");this.container=this.item.next("tr").find("td.edit-form-container");this.textSpan=this.item.find(".item-title-text");this.time=this.item.find(".time input");this.space=this.item.find(".space input");this.itemId=b===""?null:parseInt(b,10);this.recordId=c===""?null:parseInt(c,10);this.container.append(this.element);this._disableButtons();this._showContainer();
this._expandTitle();this._getFormData();_.isNull(this.itemId)?this._hideItemRecordElements():this._showItemRecordElements();this._isForm=!0}},hideForm:function(a,b){if(!this._isLocked)this._hideContainer(b),this._contractTitle(),this._isForm=!1},saveItemForm:function(){this._fadeDown();this._postFormData()},resizeForm:function(){this._measureForm();this.form.animate({height:this._nativeHeight},this.options.css.form_duration);this.dateStylesFieldset.fieldsetexpander("isExpanded")&&this.ambiguity.gradientbuilder("refresh")},
detachForm:function(){this.element.detach()},reloadForm:function(){this._getFormData()},_disableButtons:function(){this.saveButton.attr("disabled","disabled");this.deleteButton.attr("disabled","disabled")},_disableCloseButton:function(){this.closeButton.attr("disabled","disabled")},_enableButtons:function(){this.saveButton.removeAttr("disabled");this.deleteButton.removeAttr("disabled")},_enableCloseButton:function(){this.closeButton.removeAttr("disabled")},_showContainer:function(){this.container.css("display",
"table-cell");this.element.css("visibility","visible");this.form.css("height","auto")},_hideContainer:function(a){var b=this;this.form.animate({height:0},a?0:this.options.css.form_duration,function(){b.container.css("display","none")})},_expandTitle:function(){this.textSpan.css({"font-weight":"bold",color:this.options.colors.dark_purple})},_contractTitle:function(){var a=this.options.colors.text,b="normal";if(this.textSpan.data("changed"))a=this.options.colors.red,b="bold";this.textSpan.css("font-weight",
b);this.textSpan.stop().animate({color:a,"font-size":this.options.css.default_text_size},100)},_fadeDown:function(){this.element.animate({opacity:0.3},200)},_fadeUp:function(){this.element.animate({opacity:1},200)},_updateTitleText:function(){_.isNull(this.itemId)&&(this._data.title!==""?this._trigger("settitle",{},{text:this._data.title}):this._data.description!==""&&this._trigger("settitle",{},{text:this._data.description.substring(0,200)}))},_showItemRecordElements:function(){this.deleteButton.css("visibility",
"hidden");this.useDcData.removeAttr("disabled");this.useDcDataLabel.css("opacity",1)},_hideItemRecordElements:function(){this.deleteButton.css("visibility","visible");this.useDcData.attr("disabled",!0);this.useDcDataLabel.css("opacity",0.3)},_ingestData:function(a){this._data=a;this._records=a.records;this._applyData();this._enableButtons()},_applyData:function(){var a=Boolean(parseInt(this._data.use_dc_metadata,10)),b=Boolean(parseInt(this._data.show_bubble,10));this.title.val(this._data.title);
this.titleEditor.updateFrame().refresh();this.description.val(this._data.description);this.descriptionEditor.updateFrame().refresh();a?this._disableTextEditors():this._enableTextEditors();this.slug.val(this._data.slug);this.useDcData.prop("checked",a);this.showBubble.prop("checked",b);this.vectorOpacity.val(this._data.vector_opacity);this.selectOpacity.val(this._data.select_opacity);this.strokeOpacity.val(this._data.stroke_opacity);this.graphicOpacity.val(this._data.graphic_opacity);this.strokeWidth.val(this._data.stroke_width);
this.pointRadius.val(this._data.point_radius);this.pointImage.val(this._data.point_image);this.leftPercent.val(this._data.left_percent);this.rightPercent.val(this._data.right_percent);this.startDate.val(this._data.start_date);this.endDate.val(this._data.end_date);this.startVisibleDate.val(this._data.start_visible_date);this.endVisibleDate.val(this._data.end_visible_date);this.geocoverage.val(this._data.geocoverage);this.ambiguity.gradientbuilder("positionMarkers",this._data.left_percent,this._data.right_percent);
this.ambiguity.gradientbuilder("setColor",this._data.vector_color);this._opened=!0;this.vectorColor.miniColors("value",this._data.vector_color);this.strokeColor.miniColors("value",this._data.stroke_color);this.highlightColor.miniColors("value",this._data.highlight_color);this._opened=!1;this.parentRecord.empty();this.parentRecord.append(d("<option />").val("none").text("-"));_.each(this._records,_.bind(function(a,b){_.isNull(a)||this.parentRecord.append(d("<option />").val(b).text(a))},this));this.parentRecord.val(this._data.parent_record_id)},
_getData:function(){var a={};a.description=this._getDescriptionContent();a.title=this._getTitleContent();a.slug=this.slug.val();a.use_dc_metadata=this.useDcData.is(":checked")?1:0;a.show_bubble=this.showBubble.is(":checked")?1:0;a.left_percent=parseInt(this.leftPercent.val(),10);a.right_percent=parseInt(this.rightPercent.val(),10);a.start_date=this.startDate.val();a.end_date=this.endDate.val();a.start_visible_date=this.startVisibleDate.val();a.end_visible_date=this.endVisibleDate.val();a.vector_color=
this.vectorColor.val();a.stroke_color=this.strokeColor.val();a.highlight_color=this.highlightColor.val();a.vector_opacity=parseInt(this.vectorOpacity.val(),10);a.select_opacity=parseInt(this.selectOpacity.val(),10);a.stroke_opacity=parseInt(this.strokeOpacity.val(),10);a.graphic_opacity=parseInt(this.graphicOpacity.val(),10);a.stroke_width=parseInt(this.strokeWidth.val(),10);a.point_radius=parseInt(this.pointRadius.val(),10);a.point_image=this.pointImage.val();a.parent_record_id=parseInt(this.parentRecord.val(),
10);if(a.use_dc_metadata)a.description="";return a},_getDataForSave:function(){var a=this._getData();a.item_id=this.itemId;a.record_id=this.recordId;a.exhibit_id=Neatline.record.id;a.space_active=this.space.prop("checked").toString();a.time_active=this.time.prop("checked").toString();a.geocoverage=this.geocoverage.val();return a},_getDescriptionContent:function(){return this.description.next("iframe").contents().find("body").html()},_getTitleContent:function(){return this.title.next("iframe").contents().find("body").html()},
_disableTextEditors:function(){this.descriptionEditor.disable(!0);d(this.descriptionEditor.$main[0]).css("opacity",0.3)},_enableTextEditors:function(){this.descriptionEditor.disable(!1);d(this.descriptionEditor.$main[0]).css("opacity",1)},updateGeocoverage:function(a){this.geocoverage.val(a)},_getFormData:function(){d.ajax({url:"ajax/form",dataType:"json",data:{item_id:this.itemId,record_id:this.recordId,exhibit_id:Neatline.record.id},success:_.bind(function(a){this._ingestData(a)},this)})},_postFormData:function(){var a=
this,b=this._getDataForSave();d.ajax({url:"ajax/save",dataType:"json",type:"POST",data:b,success:function(b){a._fadeUp();a._trigger("savecomplete");b.statuses.space&&a._trigger("spaceactive");b.statuses.time&&a._trigger("timeactive");a._trigger("updatedid",{},{recordid:b.recordid});a._ingestData(b.form);a._updateTitleText()}})},postMapFocus:function(a,b){var c=this;d.ajax({url:"ajax/focus",type:"POST",data:{item_id:this.itemId,record_id:this.recordId,exhibit_id:Neatline.record.id,center:a,zoom:b},
success:function(){c._fadeUp();c._trigger("spaceactive");c._trigger("savecomplete")}})},postRecordDelete:function(){var a=this;d.ajax({url:"ajax/delete",type:"POST",data:{exhibit_id:Neatline.record.id,record_id:this.recordId},success:function(){a._fadeUp();a._trigger("deletecomplete")}})},postResetStyles:function(){var a=this;d.ajax({url:"ajax/resetstyles",type:"POST",data:{exhibit_id:Neatline.record.id,record_id:this.recordId},success:function(){a._fadeUp();a._trigger("savecomplete");a._getFormData()}})},
_postDcDefaultStatus:function(a){var b=this;d.ajax({url:"ajax/dcdefault",type:"POST",dataType:"html",data:{exhibit_id:Neatline.record.id,item_id:this.itemId,record_id:this.recordId,status:a?1:0},success:_.bind(function(a){this.description.val(a);this.descriptionEditor.updateFrame();b._trigger("savecomplete")},this)})},_measureForm:function(){this._nativeHeight=this.actions.position().top+this.actions.height()},getCurrentEditId:function(){return this._isForm?this.recordId:!1},insertLocalData:function(a){this._db.insert(a)},
clearLocalData:function(){this._db().remove()},getAttr:function(a){return this[a]},lockForm:function(){this._isLocked=!0;this._disableCloseButton()},unlockForm:function(){this._isLocked=!1;this._enableCloseButton()},isLocked:function(){return this._isLocked}})})(jQuery);
