/*
     http://www.apache.org/licenses/LICENSE-2.0.html Apache 2 License
*/
(function(c){c.widget("neatline.itembrowser",{options:{css:{default_text_size:14,top_margin:40,fader_width:40,container_min_width:400},colors:{light_blue:"#FFFEF8",light_yellow:"#f9f9f9",dark_purple:"#594e62",purple:"#724e85",text:"#515151",gray:"#8d8d8d",red:"#ca3c3c",orange:"#ffda82"}},_create:function(){this._window=c(window);this._body=c("body");this.topBar=c("#topbar");this.searchBox=c("#search-box");this.itemsList=c("#items-list-container");this.itemsListHeader=c("#items-list-header");this.searchCancel=
c("#search-cancel");this.neatlineContainer=c("#neatline");this.dragTip=c("#drag-tip");this.itemsTip=c("#items-tip");this.spaceTip=c("#space-tip");this.timeTip=c("#time-tip");this.itemsHeader=c("#items-header");this.spaceHeader=c("#space-header");this.timeHeader=c("#time-header");this.editForm=c("#edit-form");this.newItemButton=c("#new-item-button");this.headerRow=c("#header-row");this._searchString="";this._timeBoxes=this._spaceBoxes=this._itemsBoxes=this._currentFormItemId=this._currentFormItem=
null;this._neatlineRecords=[];this._omekaRecords=[];this._timeSorted=this._spaceSorted=this._itemsSorted=!1;this._firstRequest=!0;this._scrollTop=0;this._scrollbarWidth=c.getScrollbarWidth();this._addGlobalClasses();this._positionDivs();this._addWindowResizeListener();this._glossSearchBox();this._glossColumnHeaders();this._glossNewItemButton();this._instantiateFormManager();this._getItems()},_addGlobalClasses:function(){c.browser.mozilla&&this._body.addClass("mozilla")},_positionDivs:function(){this.element.css("width",
this.options.css.container_min_width);this._getDimensions();this.neatlineContainer.css("top",this.topBarHeight);this.element.css({width:this.containerWidth,height:this.windowHeight-this.topBarHeight-1,top:this.topBarHeight});this.containerOffset=this.element.offset();this.itemsListHeader.css({top:this.containerOffset.top,width:this.containerWidth-this._scrollbarWidth});this._positionNeatline()},_getDimensions:function(){this.containerWidth=this.element.width();this.containerHeight=this.element.height();
this.windowWidth=this._window.width();this.windowHeight=this._window.height();this.topBarHeight=this.topBar.height()},_addWindowResizeListener:function(){var a=this;this._window.bind("resize",function(){a._positionDivs()})},_positionNeatline:function(){this.neatlineContainer.css({height:this.windowHeight-this.topBarHeight,width:this.windowWidth-this.containerWidth-1});this._trigger("reposition")},_positionTitleFaders:function(){c.each(this.items,function(a,d){var d=c(d),b=d.find(".item-title-text"),
e=d.find(".item-title-fader"),b=b.height();e.css({height:b})})},_calculateTopOffset:function(a){a.data("topOffset",a.position().top)},_calculateAllTopOffsets:function(){var a=this;c.each(this.items,function(d,b){a._calculateTopOffset(c(b))})},_checkStatusBlockOn:function(a,d){a.find("."+d).find('input[type="checkbox"]').prop("checked",!0);a.data(d,!0)},_checkStatusBlockOff:function(a,d){a.find("."+d).find('input[type="checkbox"]').prop("checked",!1);a.data(d,!1)},_checkStatusBlock:function(a,d){var b=
a.find("."+d).find('input[type="checkbox"]'),c=!b.prop("checked");b.prop("checked",c);c?a.data(d,!0):a.data(d,!1)},_instantiateFormManager:function(){var a=this;this.editForm.itemform({ambiguityChange:function(d,b){var c=a._currentFormItem.attr("recordid");a._trigger("ambiguityChange",{},{recordid:c,color:b.color,leftPercent:b.leftPercent,rightPercent:b.rightPercent})},vectorColorEdit:function(d,b){if(!_.isNull(a._currentFormItem)){var c=a._currentFormItem.attr("recordid");a._trigger("vectorcoloredit",
{},{recordid:c,color:b.color})}},strokeColorEdit:function(c,b){a._trigger("strokecoloredit",{},{color:b.color})},highlightColorEdit:function(c,b){a._trigger("highlightcoloredit",{},{color:b.color})},vectorOpacityEdit:function(c,b){a._trigger("vectoropacityedit",{},{value:b.value})},strokeOpacityEdit:function(c,b){a._trigger("strokeopacityedit",{},{value:b.value})},graphicOpacityEdit:function(c,b){a._trigger("graphicopacityedit",{},{value:b.value})},strokeWidthEdit:function(c,b){a._trigger("strokewidthedit",
{},{value:b.value})},pointRadiusEdit:function(c,b){a._trigger("pointradiusedit",{},{value:b.value})},hide:function(){a._hideForm(a._currentFormItem,!0)},save:function(){a._trigger("saveform")},savecomplete:function(){a._trigger("savecomplete")},spaceactive:function(){a._checkStatusBlockOn(a._currentFormItem,"space")},timeactive:function(){a._checkStatusBlockOn(a._currentFormItem,"time")},savemapfocus:function(){a._trigger("savemapfocus")},reload:function(){a._trigger("savecomplete");a._getItems()},
settitle:function(c,b){a._currentRecordTitle.html(b.text)},updatedid:function(c,b){a._currentFormItem.attr("recordid",b.recordid);a.idToItem[parseInt(b.recordid,10)]=a._currentFormItem},deletecomplete:function(){a._currentFormItem.remove();a._hideForm(a._currentFormItem,!0);a._glossItems();a._trigger("savecomplete")}})},_glossSearchBox:function(){var a=this;this.searchBox.bind({keyup:function(){a._searchString=a.searchBox.val();a._getItems()}});this.searchCancel.bind({mousedown:function(){a.searchBox.val("");
a.searchBox.trigger("keyup")}})},_glossNewItemButton:function(){var a=this;this.newItemButton.bind({mousedown:function(){a._getNewItemMarkup()}})},_glossColumnHeaders:function(){},_recuperateScrollTop:function(){this.element.scrollTop(this._scrollTop)},_glossItems:function(){var a=this;this.items=this.itemsList.find(".item-row");this.neatlineRecordsHeader=this.itemsList.find("#neatline-header");this.omekaRecordsHeader=this.itemsList.find("#omeka-header");this._positionTitleFaders();this.idToItem=
{};this._neatlineRecords=[];this._omekaRecords=[];this._hideHeaderRows();c.each(this.items,function(d,b){var b=c(b),e=b.find("td"),f=b.attr("recordid"),i=b.find(".item-title"),k=b.find(".item-title-text"),j=b.find(".items"),n=j.find('input[type="checkbox"]'),g=b.find(".space"),l=g.find('input[type="checkbox"]'),h=b.find(".time"),m=h.find('input[type="checkbox"]');b.data("expanded",!1);b.attr("itemid")?a._omekaRecords.push(b):b.attr("recordid")&&a._neatlineRecords.push(b);c.map([b,e,i,k,g,l,h,m],function(a){a.unbind()});
a.idToItem[parseInt(f)]=b;a._calculateTopOffset(b);n.prop("checked")?b.data("items",!0):b.data("items",!1);l.prop("checked")?b.data("space",!0):b.data("space",!1);m.prop("checked")?b.data("time",!0):b.data("time",!1);c.each([l,m,n],function(a,b){b.bind("click",function(a){a.preventDefault()})});b.bind({mouseenter:function(){b.css("background-color",a.options.colors.light_blue)},mouseleave:function(){b.css("background-color",a.options.colors.light_yellow)}});j.bind({mousedown:function(){a._checkStatusBlock(b,
"items");a._saveStatus(b,"items",!0)},mouseenter:function(){j.css("background-color",a.options.colors.orange)},mouseleave:function(){j.css("background-color","")}});g.bind({mousedown:function(){a._checkStatusBlock(b,"space");a._saveStatus(b,"space",!0)},mouseenter:function(){g.css("background-color",a.options.colors.orange)},mouseleave:function(){g.css("background-color","")}});h.bind({mousedown:function(){a._checkStatusBlock(b,"time");a._saveStatus(b,"time",!0)},mouseenter:function(){h.css("background-color",
a.options.colors.orange)},mouseleave:function(){h.css("background-color","")}});i.bind({mousedown:function(){b.data("expanded")?a._hideForm(b,!0):a._showForm(b,!0,!0,!0)}})});this._itemsBoxes=this.items.find(".items");this._spaceBoxes=this.items.find(".space");this._timeBoxes=this.items.find(".time");this._calculateAllTopOffsets();this._showHeaderRows()},_insertNewRecordRow:function(a){_.isNull(this._currentFormItem)||this._hideForm(this._currentFormItem,!0);this.neatlineRecordsHeader.length===0?
this.itemsList.prepend(a):this.neatlineRecordsHeader.after(a);this._glossItems()},_showForm:function(a,c,b,e){if(!this._isEditFormLocked()){var f=a.attr("recordid");_.isNull(this._currentFormItem)||this._hideForm(this._currentFormItem,!0);this._scrollTop=this.element.scrollTop();this.editForm.itemform("showForm",a);this._trigger("itemedit",{},{recordid:f,scrollMap:c,scrollTimeline:b,focusItems:e});this._trigger("mapedit",{},{item:a,immediate:!1});a.data("expanded",!0);this._currentFormItem=a;this._currentFormItemId=
f;this._currentRecordTitle=a.find("span.item-title-text");this._hideItemRows()}},_hideForm:function(a,c){if(!this._isEditFormLocked())this.editForm.itemform("hideForm",a,c),this._trigger("endmapedit",{},{immediate:c}),a.data("expanded",!1),this._currentFormItemId=this._currentFormItem=null,this._showItemRows(),this._recuperateScrollTop()},_hideItemRows:function(){_.each(this.items,function(a){c(a).data("expanded")?c(a).show():c(a).hide()});this._hideHeaderRows();this.element.scrollTop(0)},_showItemRows:function(){_.each(this.items,
function(a){c(a).show()});this._showHeaderRows()},_hideHeaderRows:function(){this.omekaRecordsHeader.hide();this.neatlineRecordsHeader.hide()},_showHeaderRows:function(){_.isEmpty(this._omekaRecords)||this.omekaRecordsHeader.show();_.isEmpty(this._neatlineRecords)||this.neatlineRecordsHeader.show()},saveForm:function(a){this.editForm.itemform("saveItemForm",a)},_getItems:function(){var a=this;c.ajax({url:"ajax/items",dataType:"html",data:{exhibit_id:Neatline.record.id,search:this._searchString},success:function(c){a.editForm.itemform("detachForm");
a.itemsList.html(c);a._positionDivs();a._glossItems();if(a._firstRequest)a._trigger("neatlineready"),a._firstRequest=!1}})},_saveStatus:function(a,d,b){var e=this,f=a.find("."+d).find('input[type="checkbox"]').prop("checked"),i=a.attr("recordid"),k=a.attr("itemid");a.find("."+this.options.item_title_text_class);c.ajax({url:"ajax/status",type:"POST",dataType:"json",data:{exhibit_id:Neatline.record.id,item_id:k,record_id:i,space_or_time:d,value:String(f)},success:function(c){a.attr("recordid",c.record_id);
e.idToItem[c.record_id]=a;b&&e._trigger("savecomplete")}})},_getNewItemMarkup:function(){var a=this;c.ajax({url:"ajax/add",type:"GET",dataType:"html",data:{exhibit_id:Neatline.record.id},success:function(c){a._insertNewRecordRow(c)}})},setCoverageData:function(a){this.editForm.itemform("setCoverageData",a)},showFormByRecordId:function(a,c,b,e){a!=this._currentFormItemId&&this._showForm(this.idToItem[a],c,b,e)},saveMapFocus:function(a,c){this.editForm.itemform("postMapFocus",a,c)},reloadItemForm:function(){this.editForm.itemform("reloadForm")},
updateGeocoverage:function(a){this.editForm.itemform("updateGeocoverage",a)},getCurrentEditId:function(){return this.editForm.itemform("getCurrentEditId")},getAttr:function(a){return this[a]},_isEditFormLocked:function(){var a=!1;return a=this.editForm.itemform!=null&&this.editForm.itemform("isLocked")}})})(jQuery);
