/*
     http://www.apache.org/licenses/LICENSE-2.0.html Apache 2 License
*/
(function(e){e.widget("neatline.mapeditor",e.extend({},e.neatline.neatlinemap.prototype,{_create:function(){this._instantiateEditor();this.toolbar=null;return e.neatline.neatlinemap.prototype._create.apply(this,arguments)},_instantiateEditor:function(){var a=this;this.element.editgeometry({update:function(c,d){a.modifyFeatures.mode=OpenLayers.Control.ModifyFeature.RESHAPE;d.rotate&&(a.modifyFeatures.mode|=OpenLayers.Control.ModifyFeature.ROTATE);d.scale&&(a.modifyFeatures.mode|=OpenLayers.Control.ModifyFeature.RESIZE);
d.drag&&(a.modifyFeatures.mode|=OpenLayers.Control.ModifyFeature.DRAG);if(d.drag||d.rotate)a.modifyFeatures.mode&=-OpenLayers.Control.ModifyFeature.RESHAPE;var b=a.modifyFeatures.feature;b!==null&&(a.modifyFeatures.unselectFeature(b),a.modifyFeatures.selectFeature(b))},"delete":function(){if(!_.isUndefined(a.modifyFeatures)&&a.modifyFeatures.feature){var c=a.modifyFeatures.feature;a.modifyFeatures.unselectFeature(c);a._currentEditLayer.destroyFeatures([c]);a._trigger("featureadded",{},{geocoverage:a.getWktForSave()})}}})},
edit:function(a){var c=this,d=a.attr("recordid"),b=a.attr("itemid");if(d!=="")this.record=this._db({recordid:parseInt(d,10)}).first(),this._currentEditLayer=this.record.layer;else if(b!=="")this.record=this._db({itemid:parseInt(b,10)}).first(),this._currentEditLayer=this.record.layer;this._currentEditItem=a;if(!this._currentEditLayer){var f=a.find("span.item-title-text").text();this._currentEditLayer=f=new OpenLayers.Layer.Vector(f);this._currentVectorLayers.push(this._currentEditLayer);this.map.addLayer(this._currentEditLayer);
this._currentEditLayer.setMap(this.map);c._db.insert({itemid:b,layerid:f.id,recordid:d,data:a,layer:f})}this.panelControls=this._buildPanelControls();this.panelControls[0].events.register("activate",this,function(){c.element.trigger("drawingmodeoff")});d=this.panelControls.length;for(a=1;a<d;a++)b=this.panelControls[a],b.events.register("activate",this,function(){c.element.trigger("drawingmodeon")}),b.events.register("deactivate",this,function(){c.element.trigger("drawingmodeoff")});this.modifyFeatures=
new OpenLayers.Control.ModifyFeature(this._currentEditLayer,{standalone:!0,onModification:function(){c._trigger("featureadded",{},{geocoverage:c.getWktForSave()});c._addClickControls()}});this.editToolbar=new OpenLayers.Control.Panel({defaultControl:this.panelControls[0],displayClass:"olControlEditingToolbar"});this.editToolbar.addControls(this.panelControls);this.map.addControl(this.editToolbar);this.map.addControl(this.modifyFeatures);this.modifyFeatures.activate();this.toolbar=e(".olControlEditingToolbar");
this._popUpEditControls();this._positionToolbar()},endEditWithoutSave:function(){_.isUndefined(this.modifyFeatures)||(this.modifyFeatures.unselectFeature(this._clickedFeature),this.map.removeControl(this.modifyFeatures));this.map.removeControl(this.editToolbar);this.element.editgeometry("hideButtons");this.record=this._currentEditItem=null;this._addClickControls()},getWktForSave:function(){_.isUndefined(this.modifyFeatures)||this.modifyFeatures.unselectFeature(this._clickedFeature);this.cancelSketch();
var a=(new OpenLayers.Format.KML).write(this._currentEditLayer.features);if(!_.isUndefined(this.modifyFeatures)&&!_.isNull(this._clickedFeature))try{this.modifyFeatures.selectFeature(this._clickedFeature)}catch(c){}return a},cancelSketch:function(){_.each(this.panelControls.slice(1,4),function(a){a.deactivate()})},getExtentForSave:function(){return this.map.getExtent().toString()},getCenterForSave:function(){return this.map.getCenter().toShortString()},getZoomForSave:function(){return this.map.getZoom()},
getBaseLayerForSave:function(){return this.map.baseLayer.name},setCurrentRecordStyle:function(a,c){var d=this;if(!_.isNull(this.record)&&!_.isUndefined(this.record.data))this.record.data[a]=c,this._currentEditLayer.styleMap=this._getStyleMap(this.record.data.vector_color,this.record.data.vector_opacity,this.record.data.stroke_color,this.record.data.stroke_opacity,this.record.data.stroke_width,this.record.data.point_radius,this.record.data.point_image,this.record.data.highlight_color,this.record.data.select_opacity,
this.record.data.graphic_opacity),this._currentEditLayer.redraw(),e.each(this._currentEditLayer.features,function(a,c){d.highlightControl.unhighlight(c)})},setDefaultStyle:function(a,c){var d=this;this._db().each(function(b){if(_.isNull(b.data._native_styles[a]))b.data[a]=c,b.layer.styleMap=d._getStyleMap(b.data.vector_color,b.data.vector_opacity,b.data.stroke_color,b.data.stroke_opacity,b.data.stroke_width,b.data.point_radius,b.data.point_image,b.data.highlight_color,b.data.select_opacity,b.data.graphic_opacity),
e.each(b.layer.features,function(a,b){d.highlightControl.unhighlight(b)})})},_buildPanelControls:function(){var a=this;return[new OpenLayers.Control.Navigation,new OpenLayers.Control.DrawFeature(this._currentEditLayer,OpenLayers.Handler.Path,{displayClass:"olControlDrawFeaturePath",featureAdded:function(){a._trigger("featureadded",{},{geocoverage:a.getWktForSave()});a._addClickControls()}}),new OpenLayers.Control.DrawFeature(this._currentEditLayer,OpenLayers.Handler.Point,{displayClass:"olControlDrawFeaturePoint",
featureAdded:function(){a._trigger("featureadded",{},{geocoverage:a.getWktForSave()});a._addClickControls()}}),new OpenLayers.Control.DrawFeature(this._currentEditLayer,OpenLayers.Handler.Polygon,{displayClass:"olControlDrawFeaturePolygon",featureAdded:function(){a._trigger("featureadded",{},{geocoverage:a.getWktForSave()});a._addClickControls()}})]},_popUpEditControls:function(){this.element.editgeometry("showButtons",!1);this.toolbar.css("opacity",1)},_positionToolbar:function(){_.isNull(this.toolbar)||
this.toolbar.css({top:this.pos.top+17,left:this.pos.left+60})},refresh:function(a){this.pos=a;this.map.updateSize();this.positionControls(a.top,a.left,a.width,a.height);this.element.editgeometry("positionControls",a.top,a.left,a.width,a.height)}}));e.neatline.neatlinemap.defaults=e.extend({},e.neatline.neatlinemap.defaults)})(jQuery);
