module("wysihtml5.dom.getParentElement",{setup:function(){this.container=document.createElement("div")}});
test("Basic test - nodeName only",function(){this.container.innerHTML="<ul><li>foo</li></ul>";var a=this.container.querySelector("li"),c=a.firstChild,b=this.container.querySelector("ul");equal(wysihtml5.dom.getParentElement(a,{nodeName:"LI"}),a);equal(wysihtml5.dom.getParentElement(a,{nodeName:["LI","UL"]}),a);equal(wysihtml5.dom.getParentElement(a,{nodeName:"UL"}),b);equal(wysihtml5.dom.getParentElement(c,{nodeName:"UL"}),b);equal(wysihtml5.dom.getParentElement(a,{nodeName:"ul"}),null);equal(wysihtml5.dom.getParentElement(a,
{nodeName:"SPAN"}),null)});test("Check 'levels' param - nodeName only",function(){this.container.innerHTML="<div><div><ul><li></li></ul></div></div>";var a=this.container.querySelector("li"),c=this.container.querySelector("div").querySelector("div");equal(wysihtml5.dom.getParentElement(a,{nodeName:"DIV"},2),null);equal(wysihtml5.dom.getParentElement(a,{nodeName:"DIV"},3),c)});
test("Basic test - nodeName + className",function(){this.container.innerHTML='<span class="wysiwyg-color-red wysiwyg-color-green">foo</span>';var a=this.container.firstChild,c=this.container.firstChild.firstChild,b;b=wysihtml5.dom.getParentElement(c,{nodeName:"SPAN",className:"wysiwyg-color-green",classRegExp:/wysiwyg-color-[a-z]+/g});equal(b,a);b=wysihtml5.dom.getParentElement(c,{nodeName:["STRONG","SPAN"],className:"wysiwyg-color-green",classRegExp:/wysiwyg-color-[a-z]+/g});equal(b,a);b=wysihtml5.dom.getParentElement(c,
{nodeName:["STRONG"],className:"wysiwyg-color-green",classRegExp:/wysiwyg-color-[a-z]+/g});equal(b,null);b=wysihtml5.dom.getParentElement(c,{nodeName:"DIV",className:"wysiwyg-color-green",classRegExp:/wysiwyg-color-[a-z]+/g});equal(b,null);b=wysihtml5.dom.getParentElement(c,{nodeName:"SPAN",className:"wysiwyg-color-blue",classRegExp:/wysiwyg-color-[a-z]+/g});equal(b,null);b=wysihtml5.dom.getParentElement(c,{nodeName:"SPAN",className:"wysiwyg-color-red",classRegExp:/wysiwyg-color-[a-z]+/g});equal(b,
null);b=wysihtml5.dom.getParentElement(a,{nodeName:"SPAN",className:"wysiwyg-color-green",classRegExp:/wysiwyg-color-[a-z]+/g});equal(b,a);b=wysihtml5.dom.getParentElement(a,{nodeName:"span",className:"wysiwyg-color-green",classRegExp:/wysiwyg-color-[a-z]+/g});equal(b,null)});
test("Check 'levels' param - nodeName + className",function(){this.container.innerHTML='<div class="wysiwyg-color-green"><div class="wysiwyg-color-green"><ul><li></li></ul></blockquote></div></div>';var a=this.container.querySelector("li"),c=this.container.querySelector("div").querySelector("div"),b;b=wysihtml5.dom.getParentElement(a,{nodeName:"DIV",className:"wysiwyg-color-green",classRegExp:/wysiwyg-color-[a-z]+/g},2);equal(b,null);b=wysihtml5.dom.getParentElement(a,{nodeName:"DIV",className:"wysiwyg-color-green",
classRegExp:/wysiwyg-color-[a-z]+/g},3);equal(b,c)});test("Check  - no nodeName",function(){this.container.innerHTML='<div><div class="wysiwyg-text-align-right"><span>foo</span></div></div>';var a=this.container.querySelector("span"),c=this.container.querySelector("div").querySelector("div"),a=wysihtml5.dom.getParentElement(a,{className:"wysiwyg-text-align-right",classRegExp:/wysiwyg-text-align-[a-z]+/g});equal(a,c)});
test("Test - with no nodeName",function(){this.container.innerHTML='<div><div class="wysiwyg-text-align-right"><span>foo</span></div></div>';var a=this.container.querySelector("span"),c=this.container.querySelector("div").querySelector("div"),a=wysihtml5.dom.getParentElement(a,{className:"wysiwyg-text-align-right",classRegExp:/wysiwyg-text-align-[a-z]+/g});equal(a,c)});
test("Test - with only a classRegExp",function(){this.container.innerHTML='<div><div class="wysiwyg-text-align-right"><span>foo</span></div></div>';var a=this.container.querySelector("span"),c=this.container.querySelector("div").querySelector("div"),a=wysihtml5.dom.getParentElement(a,{classRegExp:/wysiwyg-text-align-[a-z]+/g});equal(a,c)});
