var TAFFY;
(function(){if(!TAFFY){var r=1,k={},e=function(a,b,c){if(a&&(f.isArray(a)&&a.length==1||!f.isArray(a)))b(f.isArray(a)?a[0]:a,0);else for(var g,d=0,a=f.isArray(a)?a:[a],l=a.length;d<l;d++)if(g=a[d],!f.isUndefined(g)||c)if(g=b(g,d),g===f.EXIT)break},n=function(a,b){var c=0,g,d;for(d in a)if(a.hasOwnProperty(d)&&(g=b(a[d],d,c++)),g===f.EXIT)break};k.extend=function(a,b){k[a]=function(){return b.apply(this,arguments)}};var t=function(a){if(f.isString(a)&&/[t][0-9]*[r][0-9]*/i.test(a))return!0;if(f.isObject(a)&&
a.___id&&a.___s)return!0;if(f.isArray(a)){var b=!0;e(a,function(a){if(!t(a))return b=!1,TAFFY.EXIT});return b}return!1},m=function(a){var b=[];f.isString(a)&&/[t][0-9]*[r][0-9]*/i.test(a)&&(a={___id:a});if(f.isArray(a))return e(a,function(a){b.push(m(a))}),function(){var a=this,g=!1;e(b,function(b){i(a,b)&&(g=!0)});return g};if(f.isObject(a))return f.isObject(a)&&a.___id&&a.___s&&(a={___id:a.___id}),n(a,function(a,g){f.isObject(a)||(a={is:a});n(a,function(a,c){var h=[];(c==="hasAll"?function(a,b){b(a)}:
e)(a,function(a){var b=!0;h.push(function(){var l;var d=this[g];c.indexOf("!")===0&&(b=!1,c=c.substring(1,c.length));return l=(d=c==="regex"?a.test(d):c==="lt"?d<a:c==="gt"?d>a:c==="lte"?d<=a:c==="gte"?d>=a:c==="left"?d.indexOf(a)===0:c==="leftnocase"?d.toLowerCase().indexOf(a.toLowerCase())===0:c==="right"?d.substring(d.length-a.length)===a:c==="rightnocase"?d.toLowerCase().substring(d.length-a.length)===a.toLowerCase():c==="like"?d.indexOf(a)>=0:c==="likenocase"?d.toLowerCase().indexOf(a.toLowerCase())>=
0:c==="is"?d===a:c==="isnocase"?d.toLowerCase()===a.toLowerCase():c==="has"?f.has(d,a):c==="hasall"?f.hasAll(d,a):c.indexOf("is")===-1&&!TAFFY.isNull(d)&&!TAFFY.isUndefined(d)&&!TAFFY.isObject(a)&&!TAFFY.isArray(a)?a===d[c]:f[c]&&f.isFunction(f[c])&&c.indexOf("is")===0?f[c](d)===a:f[c]&&f.isFunction(f[c])?f[c](d,a):b===!1)&&!b?!1:!d&&!b?!0:d,d=l})});h.length===1?b.push(h[0]):b.push(function(){var a=this,b=!1;e(h,function(c){c.apply(a)&&(b=!0)});return b})})}),function(){var a=this,g=!0,g=b.length==
1&&!b[0].apply(a)?!1:b.length==2&&(!b[0].apply(a)||!b[1].apply(a))?!1:b.length==3&&(!b[0].apply(a)||!b[1].apply(a)||!b[2].apply(a))?!1:b.length==4&&(!b[0].apply(a)||!b[1].apply(a)||!b[2].apply(a)||!b[3].apply(a))?!1:!0;b.length>4&&e(b,function(b){i(a,b)||(g=!1)});return g};if(f.isFunction(a))return a},s=function(a,b){return a.sort(function(a,g){var d=0;f.each(b,function(b){var h=b.split(" "),b=h[0],h=h.length===1?"logical":h[1];if(h==="logical"){var e=o(a[b]),i=o(g[b]);f.each(e.length<=i.length?e:
i,function(a,b){if(e[b]<i[b])return d=-1,TAFFY.EXIT;else if(e[b]>i[b])return d=1,TAFFY.EXIT})}else if(h==="logicaldesc")e=o(a[b]),i=o(g[b]),f.each(e.length<=i.length?e:i,function(a,b){if(e[b]>i[b])return d=-1,TAFFY.EXIT;else if(e[b]<i[b])return d=1,TAFFY.EXIT});else if(h==="asec"&&a[b]<g[b])return d=-1,f.EXIT;else if(h==="asec"&&a[b]>g[b])return d=1,f.EXIT;else if(h==="desc"&&a[b]>g[b])return d=-1,f.EXIT;else if(h==="desc"&&a[b]<g[b])return d=1,f.EXIT;d===0&&h==="logical"&&e.length<i.length?d=-1:
d===0&&h==="logical"&&e.length>i.length?d=1:d===0&&h==="logicaldesc"&&e.length>i.length?d=-1:d===0&&h==="logicaldesc"&&e.length<i.length&&(d=1);if(d!=0)return f.EXIT});return d})},o=null;(function(){var a={},b=0;o=function(c){b>1E3&&(a={},b=0);return a["_"+c]||function(){for(var g=String(c),d=[],f="_",e="",i=0,k=g.length;i<k;i++){var j=g.charCodeAt(i);j>=48&&j<=57||j===46?e!="n"&&(e="n",d.push(f.toLowerCase()),f=""):e!="s"&&(e="s",d.push(parseFloat(f)),f="");f+=g.charAt(i)}d.push(e==="n"?parseFloat(f):
f.toLowerCase());d.shift();a["_"+c]=d;b++;return d}()}})();var j=function(){this.context({results:this.getDBI().query(this.context())})};k.extend("filter",function(){var a=TAFFY.mergeObj(this.context(),{run:null}),b=[];e(a.q,function(a){b.push(a)});a.q=b;e(arguments,function(b){a.q.push(m(b));a.filterRaw.push(b)});return this.getroot(a)});k.extend("order",function(a){var a=a.split(","),b=[];e(a,function(a){b.push(a.replace(/^\s*/,"").replace(/\s*$/,""))});a=TAFFY.mergeObj(this.context(),{sort:null});
a.order=b;return this.getroot(a)});k.extend("limit",function(a){var b=TAFFY.mergeObj(this.context(),{});b.limit=a;if(b.run&&b.sort){var c=[];e(b.results,function(b,d){if(d+1>a)return TAFFY.EXIT;c.push(b)});b.results=c}return this.getroot(b)});k.extend("start",function(a){var b=TAFFY.mergeObj(this.context(),{});b.start=a;if(b.run&&b.sort&&!b.limit){var c=[];e(b.results,function(b,d){d+1>a&&c.push(b)});b.results=c}else b=TAFFY.mergeObj(this.context(),{run:null,start:a});return this.getroot(b)});k.extend("update",
function(){var a=!0,b={},c=arguments;TAFFY.isString(arguments[0])&&(arguments.length==2||arguments.length==3)?(b[arguments[0]]=arguments[1],arguments.length==3&&(a=arguments[2])):(b=c[0],c.length==2&&(a=c[0]));var g=this;j.call(this);e(this.context().results,function(c){var e=b;TAFFY.isFunction(e)?e=e.apply(TAFFY.mergeObj(c,{})):f.isFunction(e)&&(e=e(TAFFY.mergeObj(c,{})));TAFFY.isObject(e)&&g.getDBI().update(c.___id,e,a)});this.context().results.length&&this.context({run:null});return this});k.extend("remove",
function(a){var b=this,c=0;j.call(this);e(this.context().results,function(a){b.getDBI().remove(a.___id);c++});this.context().results.length&&(this.context({run:null}),b.getDBI().removeCommit(a));return c});k.extend("count",function(){j.call(this);return this.context().results.length});k.extend("callback",function(a,b){if(a){var c=this;setTimeout(function(){j.call(c);a.call(c.getroot(c.context()))},b?b:0)}return null});k.extend("get",function(){j.call(this);return this.context().results});k.extend("stringify",
function(){return JSON.stringify(this.get())});k.extend("first",function(){j.call(this);return this.context().results[0]||!1});k.extend("last",function(){j.call(this);return this.context().results[this.context().results.length-1]||!1});k.extend("sum",function(){var a=0;j.call(this);var b=this;e(arguments,function(c){e(b.context().results,function(b){a+=b[c]})});return a});k.extend("min",function(a){var b=null;j.call(this);e(this.context().results,function(c){if(b===null||c[a]<b)b=c[a]});return b});
k.extend("max",function(a){var b=null;j.call(this);e(this.context().results,function(c){if(b===null||c[a]>b)b=c[a]});return b});k.extend("select",function(){var a=[],b=arguments;j.call(this);arguments.length===1?e(this.context().results,function(c){a.push(c[b[0]])}):e(this.context().results,function(c){var g=[];e(b,function(a){g.push(c[a])});a.push(g)});return a});k.extend("distinct",function(){var a=[],b=arguments;j.call(this);arguments.length===1?e(this.context().results,function(c){var g=c[b[0]],
d=!1;e(a,function(a){if(g===a)return d=!0,TAFFY.EXIT});d||a.push(g)}):e(this.context().results,function(c){var g=[];e(b,function(a){g.push(c[a])});var d=!1;e(a,function(a){var c=!0;e(b,function(b,d){if(g[d]!=a[d])return c=!1,TAFFY.EXIT});if(c)return d=!0,TAFFY.EXIT});d||a.push(g)});return a});k.extend("supplant",function(a,b){var c=[];j.call(this);e(this.context().results,function(b){c.push(a.replace(/{([^{}]*)}/g,function(a,c){var f=b[c];return typeof f==="string"||typeof f==="number"?f:a}))});return!b?
c.join(""):c});k.extend("each",function(a){j.call(this);e(this.context().results,a);return this});k.extend("map",function(a){var b=[];j.call(this);e(this.context().results,function(c){b.push(a(c))});return b});var i=function(a,b){var c=!0;e(b,function(b){switch(f.typeOf(b)){case "function":if(!b.apply(a))return c=!1,TAFFY.EXIT;break;case "array":c=b.length==1?i(a,b[0]):b.length==2?i(a,b[0])||i(a,b[1]):b.length==3?i(a,b[0])||i(a,b[1])||i(a,b[2]):b.length==4?i(a,b[0])||i(a,b[1])||i(a,b[2])||i(a,b[3]):
!1,b.length>4&&e(b,function(b){i(a,b)&&(c=!0)})}});return c},f=function(a){var b=[],c={},g=1,d={template:!1,onInsert:!1,onUpdate:!1,onRemove:!1,onDBChange:!1,storageName:!1,forcePropertyCase:null,cacheSize:100},l=new Date,h=0,j=0,o={},u=function(a){if(a.length==0)return b;var d=[],g=!1;e(a,function(a){f.isString(a)&&/[t][0-9]*[r][0-9]*/i.test(a)&&b[c[a]]&&(d.push(b[c[a]]),g=!0);f.isObject(a)&&a.___id&&a.___s&&b[c[a.___id]]&&(d.push(b[c[a.___id]]),g=!0);f.isArray(a)&&e(a,function(a){e(u(a),function(a){d.push(a)})})});
g&&d.length>1&&(d=[]);return d},q={dm:function(a){a&&(l=a,o={},j=h=0);d.onDBChange&&setTimeout(function(){d.onDBChange.call(b)},0);d.storageName&&setTimeout(function(){localStorage.setItem("taffy_"+d.storageName,JSON.stringify(b))});return l},insert:function(a,i){var h=[],l=[],j=TAFFY.isArray(a)||TAFFY.isObject(a)?a:JSON.parse(a);e(j,function(a,v){if(f.isArray(a)&&v===0)return e(a,function(a){h.push(d.forcePropertyCase==="lower"?a.toLowerCase():d.forcePropertyCase==="upper"?a.toUpperCase():a)}),!0;
else if(f.isArray(a)){var j={};e(a,function(a,b){j[h[b]]=a});a=j}else if(f.isObject(a)&&d.forcePropertyCase){var k={};n(a,function(b,c){k[d.forcePropertyCase==="lower"?c.toLowerCase():d.forcePropertyCase==="upper"?c.toUpperCase():c]=a[c]});a=k}g++;a.___id="T"+String("000000"+r).slice(-6)+"R"+String("000000"+g).slice(-6);a.___s=!0;l.push(a.___id);d.template&&(a=f.mergeObj(d.template,a));b.push(a);c[a.___id]=b.length-1;d.onInsert&&(i||TAFFY.isUndefined(i))&&d.onInsert.call(a);q.dm(new Date)});return p(l)},
sort:function(a){b=s(b,a.split(","));c={};e(b,function(a,b){c[a.___id]=b});q.dm(new Date);return!0},update:function(a,e,g){var i={};d.forcePropertyCase&&(n(e,function(a,b){i[d.forcePropertyCase==="lower"?b.toLowerCase():d.forcePropertyCase==="upper"?b.toUpperCase():b]=a}),e=i);var h=b[c[a]],e=f.mergeObj(h,e),l={},j=!1;n(e,function(a,b){if(TAFFY.isUndefined(h[b])||h[b]!=a)l[b]=a,j=!0});j&&(d.onUpdate&&(g||TAFFY.isUndefined(g))&&d.onUpdate.call(e,b[c[a]],l),b[c[a]]=e,q.dm(new Date))},remove:function(a){b[c[a]].___s=
!1},removeCommit:function(a){for(var f=b.length-1;f>-1;f--)b[f].___s||(d.onRemove&&(a||TAFFY.isUndefined(a))&&d.onRemove.call(b[f]),c[b[f].___id]=void 0,b.splice(f,1));c={};e(b,function(a,b){c[a.___id]=b});q.dm(new Date)},query:function(a){var c;if(d.cacheSize){var g="";e(a.filterRaw,function(a){if(f.isFunction(a))return g="nocache",TAFFY.EXIT});g==""&&(g=JSON.stringify(f.mergeObj(a,{q:!1,run:!1,sort:!1})))}if(!a.results||!a.run||a.run&&q.dm()>a.run){var l=[];if(d.cacheSize&&o[g])return o[g].i=h++,
o[g].results;else a.q.length==0&&a.index.length==0?e(b,function(a){l.push(a)}):(c=u(a.index),e(c,function(b){(a.q.length==0||i(b,a.q))&&l.push(b)})),c=l}else c=a.results;if(a.order.length>0&&(!a.run||!a.sort))c=s(c,a.order);if(c.length&&(a.limit&&a.limit<c.length||a.start)){var k=[];e(c,function(b,c){if(!a.start||a.start&&c+1>=a.start)if(a.limit){var d=a.start?c+1-a.start:c;if(d<a.limit)k.push(b);else if(d>a.limit)return TAFFY.EXIT}else k.push(b)});c=k}d.cacheSize&&g!="nocache"&&(j++,setTimeout(function(){if(j>=
d.cacheSize*2){j=0;var a=h-d.cacheSize,b={};n(function(c,d){c.i>=a&&(b[d]=c)});o=b}},0),o[g]={i:h++,results:c});return c}},p=function(){var a=TAFFY.mergeObj(TAFFY.mergeObj(k,{insert:void 0}),{getDBI:function(){return q},getroot:function(a){return p.call(a)},context:function(a){a&&(b=TAFFY.mergeObj(b,"results"in a?TAFFY.mergeObj(a,{run:new Date,sort:new Date}):a));return b},extend:void 0}),b=this&&this.q?this:{limit:!1,start:!1,q:[],filterRaw:[],index:[],order:[],results:!1,run:null,sort:null};e(arguments,
function(a){t(a)?b.index.push(a):b.q.push(m(a));b.filterRaw.push(a)});return a};r++;a&&q.insert(a);p.insert=q.insert;p.TAFFY=!0;p.sort=q.sort;p.settings=function(a){a&&(d=TAFFY.mergeObj(d,a),a.template&&p().update(a.template));return d};p.store=function(a){if(localStorage){if(a){var c=localStorage.getItem("taffy_"+a);c&&c.length>0&&p.insert(c);b.length>0&&setTimeout(function(){localStorage.setItem("taffy_"+d.storageName,JSON.stringify(b))})}p.settings({storageName:a})}return p};return p};TAFFY=f;
f.each=e;f.eachin=n;f.extend=k.extend;TAFFY.EXIT="TAFFYEXIT";TAFFY.mergeObj=function(a,b){var c={};n(a,function(b,d){c[d]=a[d]});n(b,function(a,d){c[d]=b[d]});return c};TAFFY.has=function(a,b){var c=!0;if(a.TAFFY)return c=a(b),c.length>0?!0:!1;else switch(f.typeOf(a)){case "object":if(f.isObject(b))n(b,function(d,e){if(c===!0&&!f.isUndefined(a[e])&&a.hasOwnProperty(e))c=f.has(a[e],b[e]);else return c=!1,TAFFY.EXIT});else if(f.isArray(b))e(b,function(d,e){if(c=f.has(a,b[e]))return TAFFY.EXIT});else if(f.isString(b))if(TAFFY.isUndefined(a[b]))break;
else return!0;return c;case "array":if(f.isObject(b))e(a,function(d,e){c=f.has(a[e],b);if(c===!0)return TAFFY.EXIT});else if(f.isArray(b))e(b,function(d,g){e(a,function(d,e){c=f.has(a[e],b[g]);if(c===!0)return TAFFY.EXIT});if(c===!0)return TAFFY.EXIT});else if(f.isString(b)||f.isNumber(b))for(var g=0;g<a.length;g++)if(c=f.has(a[g],b))return!0;return c;case "string":if(f.isString(b)&&b===a)return!0;break;default:if(f.typeOf(a)===f.typeOf(b)&&a===b)return!0}return!1};TAFFY.hasAll=function(a,b){var c=
TAFFY;if(c.isArray(b)){var f=!0;e(b,function(b){f=c.has(a,b);if(f===!1)return TAFFY.EXIT});return f}else return c.has(a,b)};TAFFY.typeOf=function(a){var b=typeof a;b==="object"&&(a?typeof a.length==="number"&&!a.propertyIsEnumerable("length")&&(b="array"):b="null");return b};TAFFY.getObjectKeys=function(a){var b=[];n(a,function(a,f){b.push(f)});b.sort();return b};TAFFY.isSameArray=function(a,b){return TAFFY.isArray(a)&&TAFFY.isArray(b)&&a.join(",")===b.join(",")?!0:!1};TAFFY.isSameObject=function(a,
b){var c=TAFFY,f=!0;c.isObject(a)&&c.isObject(b)?c.isSameArray(c.getObjectKeys(a),c.getObjectKeys(b))?n(a,function(d,e){if(!(c.isObject(a[e])&&c.isObject(b[e])&&c.isSameObject(a[e],b[e])||c.isArray(a[e])&&c.isArray(b[e])&&c.isSameArray(a[e],b[e])||a[e]===b[e]))return f=!1,TAFFY.EXIT}):f=!1:f=!1;return f};(function(a){for(var b=0;b<a.length;b++)(function(a){TAFFY["is"+a]=function(b){return TAFFY.typeOf(b)===a.toLowerCase()?!0:!1}})(a[b])})("String,Number,Object,Array,Boolean,Null,Function,Undefined".split(","))}})();
if(typeof exports==="object")exports.taffy=TAFFY;var JSON;JSON||(JSON={});
(function(){function r(e){return e<10?"0"+e:e}function k(e){t.lastIndex=0;return t.test(e)?'"'+e.replace(t,function(e){var a=o[e];return typeof a==="string"?a:"\\u"+("0000"+e.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+e+'"'}function e(i,f){var a,b,c,g,d=m,l,h=f[i];h&&typeof h==="object"&&typeof h.toJSON==="function"&&(h=h.toJSON(i));typeof j==="function"&&(h=j.call(f,i,h));switch(typeof h){case "string":return k(h);case "number":return isFinite(h)?String(h):"null";case "boolean":case "null":return String(h);
case "object":if(!h)return"null";m+=s;l=[];if(Object.prototype.toString.apply(h)==="[object Array]"){g=h.length;for(a=0;a<g;a+=1)l[a]=e(a,h)||"null";c=l.length===0?"[]":m?"[\n"+m+l.join(",\n"+m)+"\n"+d+"]":"["+l.join(",")+"]";m=d;return c}if(j&&typeof j==="object"){g=j.length;for(a=0;a<g;a+=1)b=j[a],typeof b==="string"&&(c=e(b,h))&&l.push(k(b)+(m?": ":":")+c)}else for(b in h)Object.hasOwnProperty.call(h,b)&&(c=e(b,h))&&l.push(k(b)+(m?": ":":")+c);c=l.length===0?"{}":m?"{\n"+m+l.join(",\n"+m)+"\n"+
d+"}":"{"+l.join(",")+"}";m=d;return c}}if(typeof Date.prototype.toJSON!=="function")Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+r(this.getUTCMonth()+1)+"-"+r(this.getUTCDate())+"T"+r(this.getUTCHours())+":"+r(this.getUTCMinutes())+":"+r(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var n=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
t=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,m,s,o={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},j;if(typeof JSON.stringify!=="function")JSON.stringify=function(i,f,a){var b;s=m="";if(typeof a==="number")for(b=0;b<a;b+=1)s+=" ";else typeof a==="string"&&(s=a);if((j=f)&&typeof f!=="function"&&(typeof f!=="object"||typeof f.length!=="number"))throw Error("JSON.stringify");return e("",
{"":i})};if(typeof JSON.parse!=="function")JSON.parse=function(e,f){function a(b,e){var d,i,h=b[e];if(h&&typeof h==="object")for(d in h)Object.hasOwnProperty.call(h,d)&&(i=a(h,d),i!==void 0?h[d]=i:delete h[d]);return f.call(b,e,h)}var b,e=String(e);n.lastIndex=0;n.test(e)&&(e=e.replace(n,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(e.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return b=eval("("+e+")"),typeof f==="function"?a({"":b},""):b;throw new SyntaxError("JSON.parse");}})();
