/*
 Rangy, a cross-browser JavaScript range and selection library
 http://code.google.com/p/rangy/

 Copyright 2011, Tim Down
 Licensed under the MIT license.
 Version: 1.2.2
 Build date: 13 November 2011
*/
window.rangy=function(){function d(b,c){var o=typeof b[c];return o==h||!!(o==e&&b[c])||o=="unknown"}function v(b,c){return!!(typeof b[c]==e&&b[c])}function s(b,c){return typeof b[c]!=k}function t(b){return function(c,o){for(var d=o.length;d--;)if(!b(c,o[d]))return!1;return!0}}function q(b){return b&&c(b,A)&&o(b,j)}function p(b){window.alert("Rangy not supported in your browser. Reason: "+b);n.initialized=!0;n.supported=!1}function x(){if(!n.initialized){var b,e=!1,h=!1;d(document,"createRange")&&
(b=document.createRange(),c(b,l)&&o(b,m)&&(e=!0),b.detach());if((b=v(document,"body")?document.body:document.getElementsByTagName("body")[0])&&d(b,"createTextRange"))b=b.createTextRange(),q(b)&&(h=!0);!e&&!h&&p("Neither Range nor TextRange are implemented");n.initialized=!0;n.features={implementsDomRange:e,implementsTextRange:h};e=H.concat(E);h=0;for(b=e.length;h<b;++h)try{e[h](n)}catch(j){v(window,"console")&&d(window.console,"log")&&window.console.log("Init listener threw an exception. Continuing.",
j)}}}function y(b){this.name=b;this.supported=this.initialized=!1}var e="object",h="function",k="undefined",m="startContainer,startOffset,endContainer,endOffset,collapsed,commonAncestorContainer,START_TO_START,START_TO_END,END_TO_START,END_TO_END".split(","),l="setStart,setStartBefore,setStartAfter,setEnd,setEndBefore,setEndAfter,collapse,selectNode,selectNodeContents,compareBoundaryPoints,deleteContents,extractContents,cloneContents,insertNode,surroundContents,cloneRange,toString,detach".split(","),
j="boundingHeight,boundingLeft,boundingTop,boundingWidth,htmlText,text".split(","),A="collapse,compareEndPoints,duplicate,getBookmark,moveToBookmark,moveToElementText,parentElement,pasteHTML,select,setEndPoint,getBoundingClientRect".split(","),c=t(d),b=t(v),o=t(s),n={version:"1.2.2",initialized:!1,supported:!0,util:{isHostMethod:d,isHostObject:v,isHostProperty:s,areHostMethods:c,areHostObjects:b,areHostProperties:o,isTextRange:q},features:{},modules:{},config:{alertOnWarn:!1,preferTextRange:!1}};
n.fail=p;n.warn=function(b){b="Rangy warning: "+b;n.config.alertOnWarn?window.alert(b):typeof window.console!=k&&typeof window.console.log!=k&&window.console.log(b)};({}).hasOwnProperty?n.util.extend=function(b,c){for(var o in c)c.hasOwnProperty(o)&&(b[o]=c[o])}:p("hasOwnProperty not supported");var E=[],H=[];n.init=x;n.addInitListener=function(b){n.initialized?b(n):E.push(b)};var F=[];n.addCreateMissingNativeApiListener=function(b){F.push(b)};n.createMissingNativeApi=function(b){b=b||window;x();
for(var c=0,o=F.length;c<o;++c)F[c](b)};y.prototype.fail=function(b){this.initialized=!0;this.supported=!1;throw Error("Module '"+this.name+"' failed to load: "+b);};y.prototype.warn=function(b){n.warn("Module "+this.name+": "+b)};y.prototype.createError=function(b){return Error("Error in Rangy "+this.name+" module: "+b)};n.createModule=function(b,c){var o=new y(b);n.modules[b]=o;H.push(function(b){c(b,o);o.initialized=!0;o.supported=!0})};n.requireModules=function(b){for(var c=0,o=b.length,e,d;c<
o;++c){d=b[c];e=n.modules[d];if(!e||!(e instanceof y))throw Error("Module '"+d+"' not found");if(!e.supported)throw Error("Module '"+d+"' not supported");}};var D=!1,b=function(){D||(D=!0,n.initialized||x())};if(typeof window==k)p("No window found");else if(typeof document==k)p("No document found");else return d(document,"addEventListener")&&document.addEventListener("DOMContentLoaded",b,!1),d(window,"addEventListener")?window.addEventListener("load",b,!1):d(window,"attachEvent")?window.attachEvent("onload",
b):p("Window does not have required addEventListener or attachEvent method"),n}();
rangy.createModule("DomUtil",function(d,v){function s(b){for(var c=0;b=b.previousSibling;)c++;return c}function t(b,o){var e=[],d;for(d=b;d;d=d.parentNode)e.push(d);for(d=o;d;d=d.parentNode)if(c(e,d))return d;return null}function q(b,c,d){for(d=d?b:b.parentNode;d;){b=d.parentNode;if(b===c)return d;d=b}return null}function p(b){b=b.nodeType;return b==3||b==4||b==8}function x(b,c){var d=c.nextSibling,e=c.parentNode;d?e.insertBefore(b,d):e.appendChild(b);return b}function y(b){if(b.nodeType==9)return b;
else if(typeof b.ownerDocument!=l)return b.ownerDocument;else if(typeof b.document!=l)return b.document;else if(b.parentNode)return y(b.parentNode);else throw Error("getDocument: no document found for node");}function e(b){return!b?"[No node]":p(b)?'"'+b.data+'"':b.nodeType==1?"<"+b.nodeName+(b.id?' id="'+b.id+'"':"")+">["+b.childNodes.length+"]":b.nodeName}function h(b){this._next=this.root=b}function k(b,c){this.node=b;this.offset=c}function m(b){this.code=this[b];this.codeName=b;this.message="DOMException: "+
this.codeName}var l="undefined",j=d.util;j.areHostMethods(document,["createDocumentFragment","createElement","createTextNode"])||v.fail("document missing a Node creation method");j.isHostMethod(document,"getElementsByTagName")||v.fail("document missing getElementsByTagName method");var A=document.createElement("div");j.areHostMethods(A,["insertBefore","appendChild","cloneNode"])||v.fail("Incomplete Element implementation");j.isHostProperty(A,"innerHTML")||v.fail("Element is missing innerHTML property");
A=document.createTextNode("test");j.areHostMethods(A,["splitText","deleteData","insertData","appendData","cloneNode"])||v.fail("Incomplete Text Node implementation");var c=function(b,c){for(var d=b.length;d--;)if(b[d]===c)return!0;return!1};h.prototype={_current:null,hasNext:function(){return!!this._next},next:function(){var b=this._current=this._next,c;if(this._current){c=b.firstChild;if(!c)for(c=null;b!==this.root&&!(c=b.nextSibling);)b=b.parentNode;this._next=c}return this._current},detach:function(){this._current=
this._next=this.root=null}};k.prototype={equals:function(b){return this.node===b.node&this.offset==b.offset},inspect:function(){return"[DomPosition("+e(this.node)+":"+this.offset+")]"}};m.prototype={INDEX_SIZE_ERR:1,HIERARCHY_REQUEST_ERR:3,WRONG_DOCUMENT_ERR:4,NO_MODIFICATION_ALLOWED_ERR:7,NOT_FOUND_ERR:8,NOT_SUPPORTED_ERR:9,INVALID_STATE_ERR:11};m.prototype.toString=function(){return this.message};d.dom={arrayContains:c,isHtmlNamespace:function(b){var c;return typeof b.namespaceURI==l||(c=b.namespaceURI)===
null||c=="http://www.w3.org/1999/xhtml"},parentElement:function(b){b=b.parentNode;return b.nodeType==1?b:null},getNodeIndex:s,getNodeLength:function(b){var c;return p(b)?b.length:(c=b.childNodes)?c.length:0},getCommonAncestor:t,isAncestorOf:function(b,c,d){for(c=d?c:c.parentNode;c;)if(c===b)return!0;else c=c.parentNode;return!1},getClosestAncestorIn:q,isCharacterDataNode:p,insertAfter:x,splitDataNode:function(b,c){var d=b.cloneNode(!1);d.deleteData(0,c);b.deleteData(c,b.length-c);x(d,b);return d},
getDocument:y,getWindow:function(b){b=y(b);if(typeof b.defaultView!=l)return b.defaultView;else if(typeof b.parentWindow!=l)return b.parentWindow;else throw Error("Cannot get a window object for node");},getIframeWindow:function(b){if(typeof b.contentWindow!=l)return b.contentWindow;else if(typeof b.contentDocument!=l)return b.contentDocument.defaultView;else throw Error("getIframeWindow: No Window object found for iframe element");},getIframeDocument:function(b){if(typeof b.contentDocument!=l)return b.contentDocument;
else if(typeof b.contentWindow!=l)return b.contentWindow.document;else throw Error("getIframeWindow: No Document object found for iframe element");},getBody:function(b){return j.isHostObject(b,"body")?b.body:b.getElementsByTagName("body")[0]},getRootContainer:function(b){for(var c;c=b.parentNode;)b=c;return b},comparePoints:function(b,c,d,e){var h;if(b==d)return c===e?0:c<e?-1:1;else if(h=q(d,b,!0))return c<=s(h)?-1:1;else if(h=q(b,d,!0))return s(h)<e?-1:1;else if(c=t(b,d),b=b===c?c:q(b,c,!0),d=d===
c?c:q(d,c,!0),b===d)throw Error("comparePoints got to case 4 and childA and childB are the same!");else{for(c=c.firstChild;c;){if(c===b)return-1;else if(c===d)return 1;c=c.nextSibling}throw Error("Should not be here!");}},inspectNode:e,fragmentFromNodeChildren:function(b){for(var c=y(b).createDocumentFragment(),d;d=b.firstChild;)c.appendChild(d);return c},createIterator:function(b){return new h(b)},DomPosition:k};d.DOMException=m});
rangy.createModule("DomRange",function(d){function v(f,a){return f.nodeType!=3&&(g.isAncestorOf(f,a.startContainer,!0)||g.isAncestorOf(f,a.endContainer,!0))}function s(f){return g.getDocument(f.startContainer)}function t(f,a,b){if(a=f._listeners[a])for(var c=0,i=a.length;c<i;++c)a[c].call(f,{target:f,args:b})}function q(f){return new r(f.parentNode,g.getNodeIndex(f))}function p(f){return new r(f.parentNode,g.getNodeIndex(f)+1)}function x(f,a,b){var c=f.nodeType==11?f.firstChild:f;g.isCharacterDataNode(a)?
b==a.length?g.insertAfter(f,a):a.parentNode.insertBefore(f,b==0?a:g.splitDataNode(a,b)):b>=a.childNodes.length?a.appendChild(f):a.insertBefore(f,a.childNodes[b]);return c}function y(f){for(var a,b,c=s(f.range).createDocumentFragment();b=f.next();){a=f.isPartiallySelectedSubtree();b=b.cloneNode(!a);a&&(a=f.getSubtreeIterator(),b.appendChild(y(a)),a.detach(!0));if(b.nodeType==10)throw new B("HIERARCHY_REQUEST_ERR");c.appendChild(b)}return c}function e(f,a,b){for(var c,i,b=b||{stop:!1};c=f.next();)if(f.isPartiallySelectedSubtree())if(a(c)===
!1){b.stop=!0;break}else{if(c=f.getSubtreeIterator(),e(c,a,b),c.detach(!0),b.stop)break}else for(c=g.createIterator(c);i=c.next();)if(a(i)===!1){b.stop=!0;return}}function h(f){for(var a;f.next();)f.isPartiallySelectedSubtree()?(a=f.getSubtreeIterator(),h(a),a.detach(!0)):f.remove()}function k(f){for(var a,b=s(f.range).createDocumentFragment(),c;a=f.next();){f.isPartiallySelectedSubtree()?(a=a.cloneNode(!1),c=f.getSubtreeIterator(),a.appendChild(k(c)),c.detach(!0)):f.remove();if(a.nodeType==10)throw new B("HIERARCHY_REQUEST_ERR");
b.appendChild(a)}return b}function m(f,a,b){var c=!(!a||!a.length),i,d=!!b;c&&(i=RegExp("^("+a.join("|")+")$"));var z=[];e(new j(f,!1),function(f){(!c||i.test(f.nodeType))&&(!d||b(f))&&z.push(f)});return z}function l(f){return"["+(typeof f.getName=="undefined"?"Range":f.getName())+"("+g.inspectNode(f.startContainer)+":"+f.startOffset+", "+g.inspectNode(f.endContainer)+":"+f.endOffset+")]"}function j(f,a){this.range=f;this.clonePartiallySelectedTextNodes=a;if(!f.collapsed){this.sc=f.startContainer;
this.so=f.startOffset;this.ec=f.endContainer;this.eo=f.endOffset;var b=f.commonAncestorContainer;this.sc===this.ec&&g.isCharacterDataNode(this.sc)?(this.isSingleCharacterDataNode=!0,this._first=this._last=this._next=this.sc):(this._first=this._next=this.sc===b&&!g.isCharacterDataNode(this.sc)?this.sc.childNodes[this.so]:g.getClosestAncestorIn(this.sc,b,!0),this._last=this.ec===b&&!g.isCharacterDataNode(this.ec)?this.ec.childNodes[this.eo-1]:g.getClosestAncestorIn(this.ec,b,!0))}}function A(f){this.code=
this[f];this.codeName=f;this.message="RangeException: "+this.codeName}function c(f,a,b){this.nodes=m(f,a,b);this._next=this.nodes[0];this._position=0}function b(f){return function(a,b){for(var c,i=b?a:a.parentNode;i;){c=i.nodeType;if(g.arrayContains(f,c))return i;i=i.parentNode}return null}}function o(f,a){if(ba(f,a))throw new A("INVALID_NODE_TYPE_ERR");}function n(a){if(!a.startContainer)throw new B("INVALID_STATE_ERR");}function E(a,b){if(!g.arrayContains(b,a.nodeType))throw new A("INVALID_NODE_TYPE_ERR");
}function H(a,b){if(b<0||b>(g.isCharacterDataNode(a)?a.length:a.childNodes.length))throw new B("INDEX_SIZE_ERR");}function F(a,b){if(i(a,!0)!==i(b,!0))throw new B("WRONG_DOCUMENT_ERR");}function D(a){if(z(a,!0))throw new B("NO_MODIFICATION_ALLOWED_ERR");}function w(a,b){if(!a)throw new B(b);}function u(a){n(a);if(!g.arrayContains(K,a.startContainer.nodeType)&&!i(a.startContainer,!0)||!g.arrayContains(K,a.endContainer.nodeType)&&!i(a.endContainer,!0)||!(a.startOffset<=(g.isCharacterDataNode(a.startContainer)?
a.startContainer.length:a.startContainer.childNodes.length))||!(a.endOffset<=(g.isCharacterDataNode(a.endContainer)?a.endContainer.length:a.endContainer.childNodes.length)))throw Error("Range error: Range is no longer valid after DOM mutation ("+a.inspect()+")");}function G(){}function O(a){a.START_TO_START=S;a.START_TO_END=W;a.END_TO_END=ca;a.END_TO_START=X;a.NODE_BEFORE=Y;a.NODE_AFTER=Z;a.NODE_BEFORE_AND_AFTER=$;a.NODE_INSIDE=T}function J(a){O(a);O(a.prototype)}function I(a,b){return function(){u(this);
var c=this.startContainer,i=this.startOffset,d=this.commonAncestorContainer,z=new j(this,!0);if(c!==d)c=g.getClosestAncestorIn(c,d,!0),i=p(c),c=i.node,i=i.offset;e(z,D);z.reset();d=a(z);z.detach();b(this,c,i,c,i);return d}}function M(b,c,i){function e(b,f){return function(c){n(this);E(c,P);E(a(c),K);c=(b?q:p)(c);(f?z:l)(this,c.node,c.offset)}}function z(b,f,i){var d=b.endContainer,e=b.endOffset;if(f!==b.startContainer||i!==b.startOffset){if(a(f)!=a(d)||g.comparePoints(f,i,d,e)==1)d=f,e=i;c(b,f,i,
d,e)}}function l(b,f,i){var d=b.startContainer,e=b.startOffset;if(f!==b.endContainer||i!==b.endOffset){if(a(f)!=a(d)||g.comparePoints(f,i,d,e)==-1)d=f,e=i;c(b,d,e,f,i)}}b.prototype=new G;d.util.extend(b.prototype,{setStart:function(a,b){n(this);o(a,!0);H(a,b);z(this,a,b)},setEnd:function(a,b){n(this);o(a,!0);H(a,b);l(this,a,b)},setStartBefore:e(!0,!0),setStartAfter:e(!1,!0),setEndBefore:e(!0,!1),setEndAfter:e(!1,!1),collapse:function(a){u(this);a?c(this,this.startContainer,this.startOffset,this.startContainer,
this.startOffset):c(this,this.endContainer,this.endOffset,this.endContainer,this.endOffset)},selectNodeContents:function(a){n(this);o(a,!0);c(this,a,0,a,g.getNodeLength(a))},selectNode:function(a){n(this);o(a,!1);E(a,P);var b=q(a),a=p(a);c(this,b.node,b.offset,a.node,a.offset)},extractContents:I(k,c),deleteContents:I(h,c),canSurroundContents:function(){u(this);D(this.startContainer);D(this.endContainer);var a=new j(this,!0),b=a._first&&v(a._first,this)||a._last&&v(a._last,this);a.detach();return!b},
detach:function(){i(this)},splitBoundaries:function(){u(this);var a=this.startContainer,b=this.startOffset,f=this.endContainer,i=this.endOffset,d=a===f;g.isCharacterDataNode(f)&&i>0&&i<f.length&&g.splitDataNode(f,i);g.isCharacterDataNode(a)&&b>0&&b<a.length&&(a=g.splitDataNode(a,b),d?(i-=b,f=a):f==a.parentNode&&i>=g.getNodeIndex(a)&&i++,b=0);c(this,a,b,f,i)},normalizeBoundaries:function(){u(this);var a=this.startContainer,b=this.startOffset,f=this.endContainer,i=this.endOffset,d=function(a){var b=
a.nextSibling;if(b&&b.nodeType==a.nodeType)f=a,i=a.length,a.appendData(b.data),b.parentNode.removeChild(b)},e=function(c){var d=c.previousSibling;if(d&&d.nodeType==c.nodeType){a=c;var e=c.length;b=d.length;c.insertData(0,d.data);d.parentNode.removeChild(d);a==f?(i+=b,f=a):f==c.parentNode&&(d=g.getNodeIndex(c),i==d?(f=c,i=e):i>d&&i--)}},z=!0;g.isCharacterDataNode(f)?f.length==i&&d(f):(i>0&&(z=f.childNodes[i-1])&&g.isCharacterDataNode(z)&&d(z),z=!this.collapsed);z?g.isCharacterDataNode(a)?b==0&&e(a):
b<a.childNodes.length&&(d=a.childNodes[b])&&g.isCharacterDataNode(d)&&e(d):(a=f,b=i);c(this,a,b,f,i)},collapseToPoint:function(a,b){n(this);o(a,!0);H(a,b);(a!==this.startContainer||b!==this.startOffset||a!==this.endContainer||b!==this.endOffset)&&c(this,a,b,a,b)}});J(b)}function Q(a){a.collapsed=a.startContainer===a.endContainer&&a.startOffset===a.endOffset;a.commonAncestorContainer=a.collapsed?a.startContainer:g.getCommonAncestor(a.startContainer,a.endContainer)}function N(a,b,c,i,d){var e=a.startContainer!==
b||a.startOffset!==c,z=a.endContainer!==i||a.endOffset!==d;a.startContainer=b;a.startOffset=c;a.endContainer=i;a.endOffset=d;Q(a);t(a,"boundarychange",{startMoved:e,endMoved:z})}function C(a){this.startContainer=a;this.startOffset=0;this.endContainer=a;this.endOffset=0;this._listeners={boundarychange:[],detach:[]};Q(this)}d.requireModules(["DomUtil"]);var g=d.dom,r=g.DomPosition,B=d.DOMException;j.prototype={_current:null,_next:null,_first:null,_last:null,isSingleCharacterDataNode:!1,reset:function(){this._current=
null;this._next=this._first},hasNext:function(){return!!this._next},next:function(){var a=this._current=this._next;if(a)this._next=a!==this._last?a.nextSibling:null,g.isCharacterDataNode(a)&&this.clonePartiallySelectedTextNodes&&(a===this.ec&&(a=a.cloneNode(!0)).deleteData(this.eo,a.length-this.eo),this._current===this.sc&&(a=a.cloneNode(!0)).deleteData(0,this.so));return a},remove:function(){var a=this._current,b,c;g.isCharacterDataNode(a)&&(a===this.sc||a===this.ec)?(b=a===this.sc?this.so:0,c=a===
this.ec?this.eo:a.length,b!=c&&a.deleteData(b,c-b)):a.parentNode&&a.parentNode.removeChild(a)},isPartiallySelectedSubtree:function(){return v(this._current,this.range)},getSubtreeIterator:function(){var a;if(this.isSingleCharacterDataNode)a=this.range.cloneRange(),a.collapse();else{a=new C(s(this.range));var b=this._current,c=b,i=0,d=b,e=g.getNodeLength(b);if(g.isAncestorOf(b,this.sc,!0))c=this.sc,i=this.so;if(g.isAncestorOf(b,this.ec,!0))d=this.ec,e=this.eo;N(a,c,i,d,e)}return new j(a,this.clonePartiallySelectedTextNodes)},
detach:function(a){a&&this.range.detach();this.range=this._current=this._next=this._first=this._last=this.sc=this.so=this.ec=this.eo=null}};A.prototype={BAD_BOUNDARYPOINTS_ERR:1,INVALID_NODE_TYPE_ERR:2};A.prototype.toString=function(){return this.message};c.prototype={_current:null,hasNext:function(){return!!this._next},next:function(){this._current=this._next;this._next=this.nodes[++this._position];return this._current},detach:function(){this._current=this._next=this.nodes=null}};var P=[1,3,4,5,
7,8,10],K=[2,9,11],R=[1,3,4,5,7,8,10,11],L=[1,3,4,5,7,8],a=g.getRootContainer,i=b([9,11]),z=b([5,6,10,12]),ba=b([6,10,12]),aa=document.createElement("style"),U=!1;try{aa.innerHTML="<b>x</b>",U=aa.firstChild.nodeType==3}catch(da){}d.features.htmlParsingConforms=U;var V="startContainer,startOffset,endContainer,endOffset,collapsed,commonAncestorContainer".split(","),S=0,W=1,ca=2,X=3,Y=0,Z=1,$=2,T=3;G.prototype={attachListener:function(a,b){this._listeners[a].push(b)},compareBoundaryPoints:function(a,
b){u(this);F(this.startContainer,b.startContainer);var c=a==X||a==S?"start":"end",i=a==W||a==S?"start":"end";return g.comparePoints(this[c+"Container"],this[c+"Offset"],b[i+"Container"],b[i+"Offset"])},insertNode:function(a){u(this);E(a,R);D(this.startContainer);if(g.isAncestorOf(a,this.startContainer,!0))throw new B("HIERARCHY_REQUEST_ERR");this.setStartBefore(x(a,this.startContainer,this.startOffset))},cloneContents:function(){u(this);var a,b;if(this.collapsed)return s(this).createDocumentFragment();
else{if(this.startContainer===this.endContainer&&g.isCharacterDataNode(this.startContainer))return a=this.startContainer.cloneNode(!0),a.data=a.data.slice(this.startOffset,this.endOffset),b=s(this).createDocumentFragment(),b.appendChild(a),b;else b=new j(this,!0),a=y(b),b.detach();return a}},canSurroundContents:function(){u(this);D(this.startContainer);D(this.endContainer);var a=new j(this,!0),b=a._first&&v(a._first,this)||a._last&&v(a._last,this);a.detach();return!b},surroundContents:function(a){E(a,
L);if(!this.canSurroundContents())throw new A("BAD_BOUNDARYPOINTS_ERR");var b=this.extractContents();if(a.hasChildNodes())for(;a.lastChild;)a.removeChild(a.lastChild);x(a,this.startContainer,this.startOffset);a.appendChild(b);this.selectNode(a)},cloneRange:function(){u(this);for(var a=new C(s(this)),b=V.length,c;b--;)c=V[b],a[c]=this[c];return a},toString:function(){u(this);var a=this.startContainer;if(a===this.endContainer&&g.isCharacterDataNode(a))return a.nodeType==3||a.nodeType==4?a.data.slice(this.startOffset,
this.endOffset):"";else{var b=[],a=new j(this,!0);e(a,function(a){(a.nodeType==3||a.nodeType==4)&&b.push(a.data)});a.detach();return b.join("")}},compareNode:function(a){u(this);var b=a.parentNode,c=g.getNodeIndex(a);if(!b)throw new B("NOT_FOUND_ERR");a=this.comparePoint(b,c);b=this.comparePoint(b,c+1);return a<0?b>0?$:Y:b>0?Z:T},comparePoint:function(a,b){u(this);w(a,"HIERARCHY_REQUEST_ERR");F(a,this.startContainer);if(g.comparePoints(a,b,this.startContainer,this.startOffset)<0)return-1;else if(g.comparePoints(a,
b,this.endContainer,this.endOffset)>0)return 1;return 0},createContextualFragment:U?function(a){var b=this.startContainer,c=g.getDocument(b);if(!b)throw new B("INVALID_STATE_ERR");var i=null;b.nodeType==1?i=b:g.isCharacterDataNode(b)&&(i=g.parentElement(b));i=i===null||i.nodeName=="HTML"&&g.isHtmlNamespace(g.getDocument(i).documentElement)&&g.isHtmlNamespace(i)?c.createElement("body"):i.cloneNode(!1);i.innerHTML=a;return g.fragmentFromNodeChildren(i)}:function(a){n(this);var b=s(this).createElement("body");
b.innerHTML=a;return g.fragmentFromNodeChildren(b)},toHtml:function(){u(this);var a=s(this).createElement("div");a.appendChild(this.cloneContents());return a.innerHTML},intersectsNode:function(a,b){u(this);w(a,"NOT_FOUND_ERR");if(g.getDocument(a)!==s(this))return!1;var c=a.parentNode,i=g.getNodeIndex(a);w(c,"NOT_FOUND_ERR");var d=g.comparePoints(c,i,this.endContainer,this.endOffset),c=g.comparePoints(c,i+1,this.startContainer,this.startOffset);return b?d<=0&&c>=0:d<0&&c>0},isPointInRange:function(a,
b){u(this);w(a,"HIERARCHY_REQUEST_ERR");F(a,this.startContainer);return g.comparePoints(a,b,this.startContainer,this.startOffset)>=0&&g.comparePoints(a,b,this.endContainer,this.endOffset)<=0},intersectsRange:function(a,b){u(this);if(s(a)!=s(this))throw new B("WRONG_DOCUMENT_ERR");var c=g.comparePoints(this.startContainer,this.startOffset,a.endContainer,a.endOffset),i=g.comparePoints(this.endContainer,this.endOffset,a.startContainer,a.startOffset);return b?c<=0&&i>=0:c<0&&i>0},intersection:function(a){if(this.intersectsRange(a)){var b=
g.comparePoints(this.startContainer,this.startOffset,a.startContainer,a.startOffset),c=g.comparePoints(this.endContainer,this.endOffset,a.endContainer,a.endOffset),i=this.cloneRange();b==-1&&i.setStart(a.startContainer,a.startOffset);c==1&&i.setEnd(a.endContainer,a.endOffset);return i}return null},union:function(a){if(this.intersectsRange(a,!0)){var b=this.cloneRange();g.comparePoints(a.startContainer,a.startOffset,this.startContainer,this.startOffset)==-1&&b.setStart(a.startContainer,a.startOffset);
g.comparePoints(a.endContainer,a.endOffset,this.endContainer,this.endOffset)==1&&b.setEnd(a.endContainer,a.endOffset);return b}else throw new A("Ranges do not intersect");},containsNode:function(a,b){return b?this.intersectsNode(a,!1):this.compareNode(a)==T},containsNodeContents:function(a){return this.comparePoint(a,0)>=0&&this.comparePoint(a,g.getNodeLength(a))<=0},containsRange:function(a){return this.intersection(a).equals(a)},containsNodeText:function(a){var b=this.cloneRange();b.selectNode(a);
var c=b.getNodes([3]);return c.length>0?(b.setStart(c[0],0),a=c.pop(),b.setEnd(a,a.length),a=this.containsRange(b),b.detach(),a):this.containsNodeContents(a)},createNodeIterator:function(a,b){u(this);return new c(this,a,b)},getNodes:function(a,b){u(this);return m(this,a,b)},getDocument:function(){return s(this)},collapseBefore:function(a){n(this);this.setEndBefore(a);this.collapse(!1)},collapseAfter:function(a){n(this);this.setStartAfter(a);this.collapse(!0)},getName:function(){return"DomRange"},
equals:function(a){return C.rangesEqual(this,a)},inspect:function(){return l(this)}};M(C,N,function(a){n(a);a.startContainer=a.startOffset=a.endContainer=a.endOffset=null;a.collapsed=a.commonAncestorContainer=null;t(a,"detach",null);a._listeners=null});d.rangePrototype=G.prototype;C.rangeProperties=V;C.RangeIterator=j;C.copyComparisonConstants=J;C.createPrototypeRange=M;C.inspect=l;C.getRangeDocument=s;C.rangesEqual=function(a,b){return a.startContainer===b.startContainer&&a.startOffset===b.startOffset&&
a.endContainer===b.endContainer&&a.endOffset===b.endOffset};d.DomRange=C;d.RangeException=A});
rangy.createModule("WrappedRange",function(d){function v(d,h,k,m){var l=d.duplicate();l.collapse(k);var j=l.parentElement();q.isAncestorOf(h,j,!0)||(j=h);if(!j.canHaveHTML)return new p(j.parentNode,q.getNodeIndex(j));var h=q.getDocument(j).createElement("span"),s,c=k?"StartToStart":"StartToEnd";do j.insertBefore(h,h.previousSibling),l.moveToElementText(h);while((s=l.compareEndPoints(c,d))>0&&h.previousSibling);c=h.nextSibling;if(s==-1&&c&&q.isCharacterDataNode(c)){l.setEndPoint(k?"EndToStart":"EndToEnd",
d);if(/[\r\n]/.test(c.data)){j=l.duplicate();k=j.text.replace(/\r\n/g,"\r").length;for(k=j.moveStart("character",k);j.compareEndPoints("StartToEnd",j)==-1;)k++,j.moveStart("character",1)}else k=l.text.length;j=new p(c,k)}else c=(m||!k)&&h.previousSibling,j=(k=(m||k)&&h.nextSibling)&&q.isCharacterDataNode(k)?new p(k,0):c&&q.isCharacterDataNode(c)?new p(c,c.length):new p(j,q.getNodeIndex(h));h.parentNode.removeChild(h);return j}function s(d,h){var k,m,l=d.offset,j=q.getDocument(d.node),p=j.body.createTextRange(),
c=q.isCharacterDataNode(d.node);c?(k=d.node,m=k.parentNode):(k=d.node.childNodes,k=l<k.length?k[l]:null,m=d.node);j=j.createElement("span");j.innerHTML="&#feff;";k?m.insertBefore(j,k):m.appendChild(j);p.moveToElementText(j);p.collapse(!h);m.removeChild(j);if(c)p[h?"moveStart":"moveEnd"]("character",l);return p}d.requireModules(["DomUtil","DomRange"]);var t,q=d.dom,p=q.DomPosition,x=d.DomRange;if(d.features.implementsDomRange&&(!d.features.implementsTextRange||!d.config.preferTextRange))(function(){function e(c){for(var b=
k.length,d;b--;)d=k[b],c[d]=c.nativeRange[d]}var h,k=x.rangeProperties,m;t=function(c){if(!c)throw Error("Range must be specified");this.nativeRange=c;e(this)};x.createPrototypeRange(t,function(c,b,d,e,h){var j=c.endContainer!==e||c.endOffset!=h;if(c.startContainer!==b||c.startOffset!=d||j)c.setEnd(e,h),c.setStart(b,d)},function(c){c.nativeRange.detach();c.detached=!0;for(var b=k.length,d;b--;)d=k[b],c[d]=null});h=t.prototype;h.selectNode=function(c){this.nativeRange.selectNode(c);e(this)};h.deleteContents=
function(){this.nativeRange.deleteContents();e(this)};h.extractContents=function(){var c=this.nativeRange.extractContents();e(this);return c};h.cloneContents=function(){return this.nativeRange.cloneContents()};h.surroundContents=function(c){this.nativeRange.surroundContents(c);e(this)};h.collapse=function(c){this.nativeRange.collapse(c);e(this)};h.cloneRange=function(){return new t(this.nativeRange.cloneRange())};h.refresh=function(){e(this)};h.toString=function(){return this.nativeRange.toString()};
var l=document.createTextNode("test");q.getBody(document).appendChild(l);var j=document.createRange();j.setStart(l,0);j.setEnd(l,0);try{j.setStart(l,1),h.setStart=function(c,b){this.nativeRange.setStart(c,b);e(this)},h.setEnd=function(c,b){this.nativeRange.setEnd(c,b);e(this)},m=function(c){return function(b){this.nativeRange[c](b);e(this)}}}catch(p){h.setStart=function(c,b){try{this.nativeRange.setStart(c,b)}catch(d){this.nativeRange.setEnd(c,b),this.nativeRange.setStart(c,b)}e(this)},h.setEnd=function(c,
b){try{this.nativeRange.setEnd(c,b)}catch(d){this.nativeRange.setStart(c,b),this.nativeRange.setEnd(c,b)}e(this)},m=function(c,b){return function(d){try{this.nativeRange[c](d)}catch(h){this.nativeRange[b](d),this.nativeRange[c](d)}e(this)}}}h.setStartBefore=m("setStartBefore","setEndBefore");h.setStartAfter=m("setStartAfter","setEndAfter");h.setEndBefore=m("setEndBefore","setStartBefore");h.setEndAfter=m("setEndAfter","setStartAfter");j.selectNodeContents(l);h.selectNodeContents=j.startContainer==
l&&j.endContainer==l&&j.startOffset==0&&j.endOffset==l.length?function(c){this.nativeRange.selectNodeContents(c);e(this)}:function(c){this.setStart(c,0);this.setEnd(c,x.getEndOffset(c))};j.selectNodeContents(l);j.setEnd(l,3);m=document.createRange();m.selectNodeContents(l);m.setEnd(l,4);m.setStart(l,2);h.compareBoundaryPoints=j.compareBoundaryPoints(j.START_TO_END,m)==-1&j.compareBoundaryPoints(j.END_TO_START,m)==1?function(c,b){b=b.nativeRange||b;if(c==b.START_TO_END)c=b.END_TO_START;else if(c==
b.END_TO_START)c=b.START_TO_END;return this.nativeRange.compareBoundaryPoints(c,b)}:function(c,b){return this.nativeRange.compareBoundaryPoints(c,b.nativeRange||b)};if(d.util.isHostMethod(j,"createContextualFragment"))h.createContextualFragment=function(c){return this.nativeRange.createContextualFragment(c)};q.getBody(document).removeChild(l);j.detach();m.detach()})(),d.createNativeRange=function(d){return(d||document).createRange()};else if(d.features.implementsTextRange){t=function(d){this.textRange=
d;this.refresh()};t.prototype=new x(document);t.prototype.refresh=function(){var d,h,k=this.textRange;d=k.parentElement();var m=k.duplicate();m.collapse(!0);h=m.parentElement();m=k.duplicate();m.collapse(!1);k=m.parentElement();h=h==k?h:q.getCommonAncestor(h,k);h=h==d?h:q.getCommonAncestor(d,h);this.textRange.compareEndPoints("StartToEnd",this.textRange)==0?h=d=v(this.textRange,h,!0,!0):(d=v(this.textRange,h,!0,!1),h=v(this.textRange,h,!1,!1));this.setStart(d.node,d.offset);this.setEnd(h.node,h.offset)};
x.copyComparisonConstants(t);var y=function(){return this}();if(typeof y.Range=="undefined")y.Range=t;d.createNativeRange=function(d){return(d||document).body.createTextRange()}}if(d.features.implementsTextRange)t.rangeToTextRange=function(d){if(d.collapsed)return s(new p(d.startContainer,d.startOffset),!0);else{var h=s(new p(d.startContainer,d.startOffset),!0),k=s(new p(d.endContainer,d.endOffset),!1),d=q.getDocument(d.startContainer).body.createTextRange();d.setEndPoint("StartToStart",h);d.setEndPoint("EndToEnd",
k);return d}};t.prototype.getName=function(){return"WrappedRange"};d.WrappedRange=t;d.createRange=function(e){return new t(d.createNativeRange(e||document))};d.createRangyRange=function(d){return new x(d||document)};d.createIframeRange=function(e){return d.createRange(q.getIframeDocument(e))};d.createIframeRangyRange=function(e){return d.createRangyRange(q.getIframeDocument(e))};d.addCreateMissingNativeApiListener(function(e){e=e.document;if(typeof e.createRange=="undefined")e.createRange=function(){return d.createRange(this)};
e=e=null})});
rangy.createModule("WrappedSelection",function(d,v){function s(a){return(a||window).getSelection()}function t(a){return(a||window).document.selection}function q(a,b,c){var d=c?"end":"start",c=c?"start":"end";a.anchorNode=b[d+"Container"];a.anchorOffset=b[d+"Offset"];a.focusNode=b[c+"Container"];a.focusOffset=b[c+"Offset"]}function p(a){a.anchorNode=a.focusNode=null;a.anchorOffset=a.focusOffset=0;a.rangeCount=0;a.isCollapsed=!0;a._ranges.length=0}function x(a){var b;if(a instanceof o){if(b=a._selectionNativeRange,
!b)b=d.createNativeRange(c.getDocument(a.startContainer)),b.setEnd(a.endContainer,a.endOffset),b.setStart(a.startContainer,a.startOffset),a._selectionNativeRange=b,a.attachListener("detach",function(){this._selectionNativeRange=null})}else a instanceof n?b=a.nativeRange:d.features.implementsDomRange&&a instanceof c.getWindow(a.startContainer).Range&&(b=a);return b}function y(a){var b=a.getNodes(),d;a:if(!b.length||b[0].nodeType!=1)d=!1;else{d=1;for(var e=b.length;d<e;++d)if(!c.isAncestorOf(b[0],b[d])){d=
!1;break a}d=!0}if(!d)throw Error("getSingleElementFromRange: range "+a.inspect()+" did not consist of a single element");return b[0]}function e(a,b){var c=new n(b);a._ranges=[c];q(a,c,!1);a.rangeCount=1;a.isCollapsed=c.collapsed}function h(a){a._ranges.length=0;if(a.docSelection.type=="None")p(a);else{var b=a.docSelection.createRange();if(b&&typeof b.text!="undefined")e(a,b);else{a.rangeCount=b.length;for(var h,g=c.getDocument(b.item(0)),j=0;j<a.rangeCount;++j)h=d.createRange(g),h.selectNode(b.item(j)),
a._ranges.push(h);a.isCollapsed=a.rangeCount==1&&a._ranges[0].collapsed;q(a,a._ranges[a.rangeCount-1],!1)}}}function k(a,b){for(var d=a.docSelection.createRange(),e=y(b),g=c.getDocument(d.item(0)),g=c.getBody(g).createControlRange(),j=0,k=d.length;j<k;++j)g.add(d.item(j));try{g.add(e)}catch(l){throw Error("addRange(): Element within the specified Range could not be added to control selection (does it have layout?)");}g.select();h(a)}function m(a,b,c){this.nativeSelection=a;this.docSelection=b;this._ranges=
[];this.win=c;this.refresh()}function l(a,b){for(var d=c.getDocument(b[0].startContainer),d=c.getBody(d).createControlRange(),e=0,g;e<rangeCount;++e){g=y(b[e]);try{d.add(g)}catch(j){throw Error("setRanges(): Element within the one of the specified Ranges could not be added to control selection (does it have layout?)");}}d.select();h(a)}function j(a,b){if(a.anchorNode&&c.getDocument(a.anchorNode)!==c.getDocument(b))throw new E("WRONG_DOCUMENT_ERR");}function A(a){var b=[],c=new H(a.anchorNode,a.anchorOffset),
d=new H(a.focusNode,a.focusOffset),e=typeof a.getName=="function"?a.getName():"Selection";if(typeof a.rangeCount!="undefined")for(var g=0,h=a.rangeCount;g<h;++g)b[g]=o.inspect(a.getRangeAt(g));return"["+e+"(Ranges: "+b.join(", ")+")(anchor: "+c.inspect()+", focus: "+d.inspect()+"]"}d.requireModules(["DomUtil","DomRange","WrappedRange"]);d.config.checkSelectionRanges=!0;var c=d.dom,b=d.util,o=d.DomRange,n=d.WrappedRange,E=d.DOMException,H=c.DomPosition,F,D,w=d.util.isHostMethod(window,"getSelection"),
u=d.util.isHostObject(document,"selection"),G=u&&(!w||d.config.preferTextRange);G?(F=t,d.isSelectionValid=function(a){var a=(a||window).document,b=a.selection;return b.type!="None"||c.getDocument(b.createRange().parentElement())==a}):w?(F=s,d.isSelectionValid=function(){return!0}):v.fail("Neither document.selection or window.getSelection() detected.");d.getNativeSelection=F;var w=F(),O=d.createNativeRange(document),J=c.getBody(document),I=b.areHostObjects(w,b.areHostProperties(w,["anchorOffset","focusOffset"]));
d.features.selectionHasAnchorAndFocus=I;var M=b.isHostMethod(w,"extend");d.features.selectionHasExtend=M;var Q=typeof w.rangeCount=="number";d.features.selectionHasRangeCount=Q;var N=!1,C=!0;b.areHostMethods(w,["addRange","getRangeAt","removeAllRanges"])&&typeof w.rangeCount=="number"&&d.features.implementsDomRange&&function(){var a=document.createElement("iframe");J.appendChild(a);var b=c.getIframeDocument(a);b.open();b.write("<html><head></head><body>12</body></html>");b.close();var d=c.getIframeWindow(a).getSelection(),
e=b.documentElement.lastChild.firstChild,b=b.createRange();b.setStart(e,1);b.collapse(!0);d.addRange(b);C=d.rangeCount==1;d.removeAllRanges();var g=b.cloneRange();b.setStart(e,0);g.setEnd(e,2);d.addRange(b);d.addRange(g);N=d.rangeCount==2;b.detach();g.detach();J.removeChild(a)}();d.features.selectionSupportsMultipleRanges=N;d.features.collapsedNonEditableSelectionsSupported=C;var g=!1,r;J&&b.isHostMethod(J,"createControlRange")&&(r=J.createControlRange(),b.areHostProperties(r,["item","add"])&&(g=
!0));d.features.implementsControlRange=g;D=I?function(a){return a.anchorNode===a.focusNode&&a.anchorOffset===a.focusOffset}:function(a){return a.rangeCount?a.getRangeAt(a.rangeCount-1).collapsed:!1};var B;b.isHostMethod(w,"getRangeAt")?B=function(a,b){try{return a.getRangeAt(b)}catch(c){return null}}:I&&(B=function(a){var b=c.getDocument(a.anchorNode),b=d.createRange(b);b.setStart(a.anchorNode,a.anchorOffset);b.setEnd(a.focusNode,a.focusOffset);b.collapsed!==this.isCollapsed&&(b.setStart(a.focusNode,
a.focusOffset),b.setEnd(a.anchorNode,a.anchorOffset));return b});d.getSelection=function(a){var a=a||window,b=a._rangySelection,c=F(a),d=u?t(a):null;b?(b.nativeSelection=c,b.docSelection=d,b.refresh(a)):(b=new m(c,d,a),a._rangySelection=b);return b};d.getIframeSelection=function(a){return d.getSelection(c.getIframeWindow(a))};r=m.prototype;if(!G&&I&&b.areHostMethods(w,["removeAllRanges","addRange"])){r.removeAllRanges=function(){this.nativeSelection.removeAllRanges();p(this)};var P=function(a,b){var c=
o.getRangeDocument(b),c=d.createRange(c);c.collapseToPoint(b.endContainer,b.endOffset);a.nativeSelection.addRange(x(c));a.nativeSelection.extend(b.startContainer,b.startOffset);a.refresh()};r.addRange=Q?function(a,b){if(g&&u&&this.docSelection.type=="Control")k(this,a);else if(b&&M)P(this,a);else{var c;N?c=this.rangeCount:(this.removeAllRanges(),c=0);this.nativeSelection.addRange(x(a));this.rangeCount=this.nativeSelection.rangeCount;this.rangeCount==c+1?(d.config.checkSelectionRanges&&(c=B(this.nativeSelection,
this.rangeCount-1))&&!o.rangesEqual(c,a)&&(a=new n(c)),this._ranges[this.rangeCount-1]=a,q(this,a,L(this.nativeSelection)),this.isCollapsed=D(this)):this.refresh()}}:function(a,b){b&&M?P(this,a):(this.nativeSelection.addRange(x(a)),this.refresh())};r.setRanges=function(a){if(g&&a.length>1)l(this,a);else{this.removeAllRanges();for(var b=0,c=a.length;b<c;++b)this.addRange(a[b])}}}else if(b.isHostMethod(w,"empty")&&b.isHostMethod(O,"select")&&g&&G)r.removeAllRanges=function(){try{if(this.docSelection.empty(),
this.docSelection.type!="None"){var a;if(this.anchorNode)a=c.getDocument(this.anchorNode);else if(this.docSelection.type=="Control"){var b=this.docSelection.createRange();b.length&&(a=c.getDocument(b.item(0)).body.createTextRange())}a&&(a.body.createTextRange().select(),this.docSelection.empty())}}catch(d){}p(this)},r.addRange=function(a){this.docSelection.type=="Control"?k(this,a):(n.rangeToTextRange(a).select(),this._ranges[0]=a,this.rangeCount=1,this.isCollapsed=this._ranges[0].collapsed,q(this,
a,!1))},r.setRanges=function(a){this.removeAllRanges();var b=a.length;b>1?l(this,a):b&&this.addRange(a[0])};else return v.fail("No means of selecting a Range or TextRange was found"),!1;r.getRangeAt=function(a){if(a<0||a>=this.rangeCount)throw new E("INDEX_SIZE_ERR");else return this._ranges[a]};var K;if(G)K=function(a){var b;d.isSelectionValid(a.win)?b=a.docSelection.createRange():(b=c.getBody(a.win.document).createTextRange(),b.collapse(!0));a.docSelection.type=="Control"?h(a):b&&typeof b.text!=
"undefined"?e(a,b):p(a)};else if(b.isHostMethod(w,"getRangeAt")&&typeof w.rangeCount=="number")K=function(a){if(g&&u&&a.docSelection.type=="Control")h(a);else if(a._ranges.length=a.rangeCount=a.nativeSelection.rangeCount,a.rangeCount){for(var b=0,c=a.rangeCount;b<c;++b)a._ranges[b]=new d.WrappedRange(a.nativeSelection.getRangeAt(b));q(a,a._ranges[a.rangeCount-1],L(a.nativeSelection));a.isCollapsed=D(a)}else p(a)};else if(I&&typeof w.isCollapsed=="boolean"&&typeof O.collapsed=="boolean"&&d.features.implementsDomRange)K=
function(a){var b;b=a.nativeSelection;b.anchorNode?(b=B(b,0),a._ranges=[b],a.rangeCount=1,b=a.nativeSelection,a.anchorNode=b.anchorNode,a.anchorOffset=b.anchorOffset,a.focusNode=b.focusNode,a.focusOffset=b.focusOffset,a.isCollapsed=D(a)):p(a)};else return v.fail("No means of obtaining a Range or TextRange from the user's selection was found"),!1;r.refresh=function(a){var b=a?this._ranges.slice(0):null;K(this);if(a){a=b.length;if(a!=this._ranges.length)return!1;for(;a--;)if(!o.rangesEqual(b[a],this._ranges[a]))return!1;
return!0}};var R=function(a,b){var c=a.getAllRanges(),d=!1;a.removeAllRanges();for(var e=0,g=c.length;e<g;++e)d||b!==c[e]?a.addRange(c[e]):d=!0;a.rangeCount||p(a)};r.removeRange=g?function(a){if(this.docSelection.type=="Control"){for(var b=this.docSelection.createRange(),a=y(a),d=c.getDocument(b.item(0)),d=c.getBody(d).createControlRange(),e,g=!1,j=0,k=b.length;j<k;++j)e=b.item(j),e!==a||g?d.add(b.item(j)):g=!0;d.select();h(this)}else R(this,a)}:function(a){R(this,a)};var L;!G&&I&&d.features.implementsDomRange?
(L=function(a){var b=!1;a.anchorNode&&(b=c.comparePoints(a.anchorNode,a.anchorOffset,a.focusNode,a.focusOffset)==1);return b},r.isBackwards=function(){return L(this)}):L=r.isBackwards=function(){return!1};r.toString=function(){for(var a=[],b=0,c=this.rangeCount;b<c;++b)a[b]=""+this._ranges[b];return a.join("")};r.collapse=function(a,b){j(this,a);var e=d.createRange(c.getDocument(a));e.collapseToPoint(a,b);this.removeAllRanges();this.addRange(e);this.isCollapsed=!0};r.collapseToStart=function(){if(this.rangeCount){var a=
this._ranges[0];this.collapse(a.startContainer,a.startOffset)}else throw new E("INVALID_STATE_ERR");};r.collapseToEnd=function(){if(this.rangeCount){var a=this._ranges[this.rangeCount-1];this.collapse(a.endContainer,a.endOffset)}else throw new E("INVALID_STATE_ERR");};r.selectAllChildren=function(a){j(this,a);var b=d.createRange(c.getDocument(a));b.selectNodeContents(a);this.removeAllRanges();this.addRange(b)};r.deleteFromDocument=function(){if(g&&u&&this.docSelection.type=="Control"){for(var a=this.docSelection.createRange(),
b;a.length;)b=a.item(0),a.remove(b),b.parentNode.removeChild(b);this.refresh()}else if(this.rangeCount){a=this.getAllRanges();this.removeAllRanges();b=0;for(var c=a.length;b<c;++b)a[b].deleteContents();this.addRange(a[c-1])}};r.getAllRanges=function(){return this._ranges.slice(0)};r.setSingleRange=function(a){this.setRanges([a])};r.containsNode=function(a,b){for(var c=0,d=this._ranges.length;c<d;++c)if(this._ranges[c].containsNode(a,b))return!0;return!1};r.toHtml=function(){var a="";if(this.rangeCount){for(var a=
o.getRangeDocument(this._ranges[0]).createElement("div"),b=0,c=this._ranges.length;b<c;++b)a.appendChild(this._ranges[b].cloneContents());a=a.innerHTML}return a};r.getName=function(){return"WrappedSelection"};r.inspect=function(){return A(this)};r.detach=function(){this.win=this.anchorNode=this.focusNode=this.win._rangySelection=null};m.inspect=A;d.Selection=m;d.selectionPrototype=r;d.addCreateMissingNativeApiListener(function(a){if(typeof a.getSelection=="undefined")a.getSelection=function(){return d.getSelection(this)};
a=null})});
