/*
     http://www.apache.org/licenses/LICENSE-2.0.html Apache 2 License
*/
(function(d){d.widget("neatline.neatlineitems",{options:{colors:{purple:"#724E85",background:"#f9f9f9",title:"#202020"},css:{def_opacity:0.7,def_font_size:13,active_font_size:18}},_create:function(){this._window=d(window);this._body=d("body");this.listContainer=d("#items-container");this._idToItem={};this._slugToItem={};this._idToOffset={};this._currentRecordId=this._currentRecord=null;this._idOrdering=[];this._db=TAFFY();this._getItems();this._addResizeListener()},loadData:function(){this._getItems()},
_getItems:function(){var a=this;d.ajax({url:Neatline.dataSources.undated,dataType:"json",success:function(b){a._renderItems(b);a._trigger("newitems");a._setStartingVisibility()}})},_addResizeListener:function(){var a=this;this._window.bind("resize",function(){a._getItemOffsets()})},_renderItems:function(a){this._db=TAFFY();this.listContainer.empty();_.each(a,_.bind(function(a){var e=d('<li class="item-title" />'),c=d('<li class="item-description" />');e.html(a.title);e.attr("recordid",a.id);c.html(a.description);
this.listContainer.append(e,c);e.data("expanded",!1);this._idOrdering.push(a.id);var f={recordid:a.id,slug:a.slug,title:e,description:c,start_visible_date:a.start_visible_date,end_visible_date:a.end_visible_date};this._db.insert(f);e.bind({mousedown:_.bind(function(){e.data("expanded")?this.contractDescription(f):(this.scrollToItem(a.id),this._trigger("itemclick",{},{recordid:a.id,slug:a.slug,scrollItems:!0}))},this),mouseenter:_.bind(function(){this._trigger("itementer",{},{recordid:a.id,slug:a.slug})},
this),mouseleave:_.bind(function(){this._trigger("itemleave",{},{recordid:a.id,slug:a.slug})},this)})},this));this._getItemOffsets()},scrollRight:function(){var a=this.getNewScrollId("right"),b=this._db({recordid:a}).first();this._trigger("itemclick",{},{recordid:a,slug:b.slug,scrollItems:!0})},scrollLeft:function(){var a=this.getNewScrollId("left"),b=this._db({recordid:a}).first();this._trigger("itemclick",{},{recordid:a,slug:b.slug,scrollItems:!0})},getNewScrollId:function(a){switch(a){case "left":return _.isNull(this._currentRecordId)?
this._idOrdering[this._idOrdering.length-1]:(a=this._idOrdering.indexOf(this._currentRecordId),a===0?this._idOrdering[this._idOrdering.length-1]:this._idOrdering[a-1]);case "right":return _.isNull(this._currentRecordId)?this._idOrdering[0]:(a=this._idOrdering.indexOf(this._currentRecordId),a===this._idOrdering.length-1?this._idOrdering[0]:this._idOrdering[a+1])}},_getItemOffsets:function(){var a=this;this.items=this.listContainer.find(".item-title");this._idToOffset={};d.each(this.items,function(b,
e){var e=d(e),c=e.attr("recordid");a._idToOffset[c]=e.position().top})},expandDescription:function(a){this.__activateTitle(a);a.description.html()!==""&&(a.description.css("display","list-item"),a.description.animate({height:a.description[0].scrollHeight},200));this._currentRecord=a;this._currentRecordId=a.recordid;a.title.data("expanded",!0)},contractDescription:function(a){this.__deactivateTitle(a);a.description.animate({height:0},200,function(){a.description.css("display","none")});this._currentRecordId=
this._currentRecord=null;a.title.data("expanded",!1)},renderVisibility:function(a){var b=moment(a);this._db().each(_.bind(function(a){var c=moment(a.start_visible_date),d=moment(a.end_visible_date);!_.isNull(c)&&!_.isNull(d)?(c=b>c&&b<d,this._displayRecord(a,c)):!_.isNull(c)&&_.isNull(d)?(c=b>c,this._displayRecord(a,c)):_.isNull(c)&&!_.isNull(d)&&(c=b<d,this._displayRecord(a,c))},this))},_setStartingVisibility:function(){Neatline.record.default_focus_date?this.renderVisibility(Neatline.record.default_focus_date):
this.renderVisibility(Date.now())},scrollToItem:function(a){this._showRecord(this._db({recordid:parseInt(a,10)}).first())},scrollToItemBySlug:function(a){this._showRecord(this._db({slug:a}).first())},_displayRecord:function(a,b){b?(a.title.css("display","list-item"),a.title.data("expanded")&&a.description.html()!==""&&a.description.css("display","list-item")):(a.title.css("display","none"),a.description.css("display","none"))},_showRecord:function(a){if(a){this._currentRecordId!==null&&this._currentRecordId!==
a.recordid&&(this.__hideCurrentDescription(),this._currentRecord.title.data("expanded",!1));var b=a.title.position().top+this.element.scrollTop();if(b>this.element[0].scrollHeight)b=this.element[0].scrollHeight;this.element.animate({scrollTop:b+1},200);this.expandDescription(a)}},__activateTitle:function(a){a.title.data("expanded")||(a.title.addClass("selected"),this._trigger("itemactivate",{},{recordid:a.recordid,slug:a.slug,scrollItems:!0}))},__deactivateTitle:function(a){a.title.data("expanded")&&
(a.title.removeClass("selected"),this._trigger("itemdeactivate",{},{recordid:a.recordid,slug:a.slug,scrollItems:!0}))},__hideCurrentDescription:function(){_.isNull(this._currentRecord)||(this.__deactivateTitle(this._currentRecord),this._currentRecord.description.css({height:0,display:"none"}))},getAttr:function(a){return this[a]},setAttr:function(a,b){return this[a]=b}})})(jQuery);
