/*
     http://www.apache.org/licenses/LICENSE-2.0.html Apache 2 License
*/
(function(e){e.widget("neatline.neatline",{options:{isPublic:!0,markup:{map_id:"map",timeline_id:"timeline",items_id:"items",scroller:"scroll"}},_create:function(){this.params=Neatline;this._window=e(window);this._body=e("body");this.map=e("#"+this.options.markup.map_id);this.timeline=e("#"+this.options.markup.timeline_id);this.items=e("#"+this.options.markup.items_id);this.scroller=e("#"+this.options.markup.scroller);this.instantiated_undated=this.instantiated_timeline=this.instantiated_map=!1;this.frozenOut=
null;this._getMajorBlock();this._instantiatePositioner();this.positionDivs();this.instantiateBlocks();this.instantiateBubbles();this.refreshDivs();this.element.disableSelection();this._window.resize(_.bind(function(){this.positionDivs()},this))},_instantiatePositioner:function(){var a=this;this.element.positioner({markup:{map:"#"+this.options.markup.map_id,timeline:"#"+this.options.markup.timeline_id,items:"#"+this.options.markup.items_id},constants:{h_percent:this.params.proportions.horizontal,v_percent:this.params.proportions.vertical},
drag:function(c,d){a._trigger("widthdrag",{},d);a.timeline.neatlinetimeline("refresh")},layoutChange:function(){a.timeline.neatlinetimeline("refresh")}})},setParams:function(a){this.params.record=a;this._getMajorBlock()},_getMajorBlock:function(){if(this.params.record.is_map&&this.params.record.is_timeline)if(this.params.record.top_element==="map")this.majorBlock=this.map,this.majorBlockId="map";else{if(this.params.record.top_element==="timeline")this.majorBlock=this.timeline,this.majorBlockId="timeline"}else if(this.params.record.is_map)this.majorBlock=
this.map,this.majorBlockId="map";else if(this.params.record.is_timeline)this.majorBlock=this.timeline,this.majorBlockId="timeline"},positionDivs:function(){this.element.positioner("measure");this.positions=this.element.positioner("compute",this.params.record.is_map,this.params.record.is_timeline,this.params.record.is_items,this.params.record.top_element,this.params.record.items_v_pos,this.params.record.items_h_pos,this.params.record.items_height);this.element.positioner("apply");this.refreshDivs()},
refreshDivs:function(){this.timeline.neatlinetimeline("refresh");this.options.isPublic?this.map.neatlinemap("refresh",this.positions.map):this.map.mapeditor("refresh",this.positions.map)},_getContainerDimensions:function(){this.containerWidth=this.element.width();this.containerHeight=this.element.height()},instantiateBlocks:function(){var a=this;if(this.params.record.is_map&&!this.instantiated_map){var c={featureadded:function(d,b){a._trigger("mapfeatureadded",{},b)},featureenter:function(d,b){a._trigger("mapfeatureenter",
{},b);if(a.options.isPublic&&b.record.data.show_bubble==1&&(!b.record.selected||a.items.length===0))a.freezeOut(b.record.data),a.element.bubbles("show",b.record.data.title,b.record.data.description)},featureleave:function(d,b){var c=jQuery(a.element).data("bubbles");a._trigger("mapfeatureleave",{},b);a.options.isPublic&&c!=null&&c.bubble!=null&&c.hide();a.thawOut(!0);a._trigger("mapfeatureleave",{},b)},featureclick:function(c,b){a._trigger("mapfeatureclick",{},b);a.options.isPublic&&(a.useFrozen(),
a.element.bubbles("freeze"))},featureunselect:function(c,b){a.options.isPublic&&a.element.bubbles("getTitle")===b.record.data.title&&a.element.bubbles("close");a.thawOut()}};this.options.isPublic?this.map.neatlinemap(c):this.map.mapeditor(c);this.map.data("neatlinemap").map.events.register("mouseout",{},function(){});this.instantiated_map=!0}if(this.params.record.is_timeline&&!this.instantiated_timeline)this.timeline.neatlinetimeline({scroll:function(c,b){a.map.neatlinemap("renderVisibility",b.date);
a.items.neatlineitems("renderVisibility",b.date)},evententer:function(c,b){a.options.isPublic&&b.show_bubble==1&&a.element.bubbles("show",b.title,b.description)},eventleave:function(){a.options.isPublic&&a.element.bubbles("hide")},eventclick:function(c,b){a._trigger("timelineeventclick",{},b);a.options.isPublic&&a.element.bubbles("freeze")}}),this.instantiated_timeline=!0;if(this.params.record.is_items&&!this.instantiated_undated)c={itemclick:function(c,b){a._trigger("itemclick",{},b)},itementer:function(c,
b){a._trigger("itementer",{},b);a.map.neatlinemap("highlightVectors",b.recordid)},itemleave:function(c,b){a._trigger("itemleave",{},b);a.map.neatlinemap("unhighlightVectors",b.recordid)},itemactivate:function(c,b){a._trigger("itemactivate",{},b);a.map.neatlinemap("selectVectors",b.recordid)},itemdeactivate:function(c,b){a._trigger("itemdeactivate",{},b);a.map.neatlinemap("unselectVectors",b.recordid)}},this.options.isPublic?this.items.neatlineitems(c):this.items.itemorderer(c),this.instantiated_undated=
!0},instantiateBubbles:function(){this.element.bubbles({cursorleave:_.bind(function(){this.map.neatlinemap("unhighlightHoveredRecord")},this),close:_.bind(function(){this.map.neatlinemap("unselectSelectedRecord")},this)})},freezeOut:function(a){if(this.element.bubbles("isFrozen")){var c=e(window),d=this;this.frozenOut={data:a,event:null};c.on("mousemove.frozen",function(a){_.isNull(d.frozenOut)?c.off("mousemove.frozen"):d.frozenOut.event=a})}},thawOut:function(a){if(!_.isNull(this.frozenOut)&&(a||
this.frozenOut.data.title==this.element.bubbles("getTitle")))e(window).off("mousemove.frozen"),this.frozenOut=null},useFrozen:function(){if(!_.isNull(this.frozenOut)){var a=this.element;a.bubbles("show",this.frozenOut.data.title,this.frozenOut.data.description);a.bubbles("position",this.frozenOut.event);this.thawOut(!0)}},positionBlockMarkup:function(){this.items.neatlineitems("positionMarkup")},saveSuccess:function(){this.element.css("opacity",0);this.element.animate({opacity:1},500)},editMap:function(a,
c){this.map.neatlinemap("edit",a,c)},endMapEditWithoutSave:function(a){this.map.neatlinemap("endEditWithoutSave",a)},getWktForSave:function(){return this.instantiated_map?this.map.neatlinemap("getWktForSave"):null},reloadTimeline:function(){this.timeline.neatlinetimeline("loadData")},reloadMap:function(){this.map.neatlinemap("loadData")},reloadItems:function(){this.items.neatlineitems("loadData")},zoomMapToItemVectors:function(a){this.map.neatlinemap("zoomToItemVectors",a)},zoomMapToItemVectorsBySlug:function(a){this.map.neatlinemap("zoomToItemVectorsBySlug",
a)},zoomTimelineToEvent:function(a){this.timeline.neatlinetimeline("zoomToEvent",a)},zoomTimelineToEventBySlug:function(a){this.timeline.neatlinetimeline("zoomToEventBySlug",a)},showItemDescription:function(a){this.items.neatlineitems("scrollToItem",a)},showItemDescriptionBySlug:function(a){this.items.neatlineitems("scrollToItemBySlug",a)},setItemVectorColor:function(a,c){this.map.neatlinemap("setCurrentRecordStyle","vector_color",a);this.timeline.neatlinetimeline("setDateColor",c,a)},setItemStrokeColor:function(a){this.map.neatlinemap("setCurrentRecordStyle",
"stroke_color",a)},setItemHighlightColor:function(a){this.map.neatlinemap("setCurrentRecordStyle","highlight_color",a)},setItemVectorOpacity:function(a){this.map.neatlinemap("setCurrentRecordStyle","vector_opacity",a/100)},setItemStrokeOpacity:function(a){this.map.neatlinemap("setCurrentRecordStyle","stroke_opacity",a/100)},setItemGraphicOpacity:function(a){this.map.neatlinemap("setCurrentRecordStyle","graphic_opacity",a/100)},setItemStrokeWidth:function(a){this.map.neatlinemap("setCurrentRecordStyle",
"stroke_width",a)},setItemPointRadius:function(a){this.map.neatlinemap("setCurrentRecordStyle","point_radius",a)},setDefaultVectorColor:function(a){this.map.neatlinemap("setDefaultStyle","vector_color",a);this.timeline.neatlinetimeline("setDefaultDateColor",a)},setDefaultStrokeColor:function(a){this.map.neatlinemap("setDefaultStyle","stroke_color",a)},setDefaultHighlightColor:function(a){this.map.neatlinemap("setDefaultStyle","highlight_color",a)},setDefaultVectorOpacity:function(a){this.map.neatlinemap("setDefaultStyle",
"vector_opacity",a/100)},setDefaultStrokeOpacity:function(a){this.map.neatlinemap("setDefaultStyle","stroke_opacity",a/100)},setDefaultStrokeWidth:function(a){this.map.neatlinemap("setDefaultStyle","stroke_width",a)},setDefaultPointRadius:function(a){this.map.neatlinemap("setDefaultStyle","point_radius",a)},setDateAmbiguity:function(a,c,d,b){this.timeline.neatlinetimeline("setDateAmbiguity",a,c,d,b)},highlightMapBySlug:function(a){this.map.neatlinemap("highlightVectorsBySlug",a)},unhighlightMapBySlug:function(a){this.map.neatlinemap("unhighlightVectorsBySlug",
a)},unselectMapSelectedRecord:function(){this.map.neatlinemap("unselectSelectedRecord")},getMapExtent:function(){return this.map.neatlinemap("getExtentForSave")},getMapCenter:function(){return this.map.neatlinemap("getCenterForSave")},getMapZoom:function(){return this.map.neatlinemap("getZoomForSave")},getMapBaseLayer:function(){return this.map.neatlinemap("getBaseLayerForSave")},getTimelineCenter:function(){return this.instantiated_timeline?this.timeline.neatlinetimeline("getCenterForSave"):null},
getTimelineZoom:function(){return this.instantiated_timeline?this.timeline.neatlinetimeline("getZoomForSave"):null},reorderItems:function(){this.items.neatlineitems("reorder")},getOrder:function(){return this.items.neatlineitems("objectifyOrder")},endReorderItems:function(){return this.items.neatlineitems("endreorder")},renderTimelineDefaults:function(a,c,d){this.timeline.neatlinetimeline("renderDefaults",a,c,d)},applyViewportProportions:function(a,c){this.element.positioner("applyProportions",a,
c);this.timeline.neatlinetimeline("refresh")}})})(jQuery);
