/*
     http://www.apache.org/licenses/LICENSE-2.0.html Apache 2 License
*/
(function(e,i){e.widget("neatline.neatlinemap",{options:{mode:"edit",wkt_delimiter:"|",animation:{fade_duration:500},colors:{neatline_purple:"#724E85",highlight_red:"#d04545"},styles:{vector_color:"#ffb80e",stroke_color:"#ea3a3a",highlight_color:"#ff0000",vector_opacity:0.4,stroke_opacity:0.6,stroke_width:1,point_radius:6}},_create:function(){this._window=e(window);this._db=TAFFY();this._currentVectorLayers=[];this.requestData=this.record=this._clickedFeature=this._hoveredFeature=this._selectedRecord=
this._hoveredRecord=this._currentEditLayer=this._currentEditItem=null;this.now=Date.now();Neatline.record.image_id?this._instantiateImageMap():this._instantiateRealGeographyMap();this.loadData()},_instantiateRealGeographyMap:function(){OpenLayers.IMAGE_RELOAD_ATTEMTPS=3;OpenLayers.Util.onImageLoadErrorColor="transparent";OpenLayers.ImgPath="http://js.mapbox.com/theme/dark/";OpenLayers.IMAGE_RELOAD_ATTEMPTS=5;OpenLayers.DOTS_PER_INCH=25.4/0.28;new OpenLayers.Bounds(-8344149.6594826,4855703.4254752,
-8119424.7963554,5104888.1376502);this.mousePosition=new OpenLayers.Control.MousePosition;var a={controls:[this.mousePosition,new OpenLayers.Control.PanZoomBar,new OpenLayers.Control.Navigation({documentDrag:!0}),new OpenLayers.Control.LayerSwitcher],maxResolution:"auto",units:"m"};this.map=new OpenLayers.Map("map",a);this.map.addLayers(this._getBaseLayers());this._setDefaultLayer();this.setViewport(Neatline.record.default_map_bounds,Neatline.record.default_map_zoom)||(a=new OpenLayers.Control.Geolocate({bind:!0,
watch:!1}),a.events.on({locationfailed:function(){self.map.setCenter(new OpenLayers.LonLat(-8738850.21367,4584105.47978),3,!1,!1)}}),this.map.addControl(a),this.map.zoomTo(6),a.activate())},_instantiateImageMap:function(){OpenLayers.IMAGE_RELOAD_ATTEMTPS=3;OpenLayers.Util.onImageLoadErrorColor="transparent";OpenLayers.ImgPath="http://js.mapbox.com/theme/dark/";OpenLayers.DOTS_PER_INCH=25.4/0.28;var a={controls:[new OpenLayers.Control.PanZoomBar,new OpenLayers.Control.MousePosition,new OpenLayers.Control.Navigation],
maxResolution:"auto"};this.map=new OpenLayers.Map("map",a);var b=new OpenLayers.Bounds(0,0,Neatline.image.width,Neatline.image.height),c=new OpenLayers.Size(Neatline.image.width,Neatline.image.height);this.baseLayer=new OpenLayers.Layer.Image(Neatline.image.name,Neatline.image.path,b,c,a);this.map.addLayers([this.baseLayer]);this.setViewport(Neatline.record.default_map_bounds,Neatline.record.default_map_zoom)||this.map.zoomToExtent(b)},positionControls:function(a,b,c){this.panZoomBar=this.element.find(".olControlPanZoomBar");
this.layerSwitcher=this.element.find(".olControlLayerSwitcher");var d=this.element.width();this.element.height();this.layerSwitcher.css({top:a+25,right:d-(b+c)});this.panZoomBar.css({top:a+10,left:b+5})},loadData:function(){var a=this;this._removeSelectControls();this._removeEditControls();_.each(this._currentVectorLayers,function(b){a.map.removeLayer(b);b.destroy()});_.each(this._wmsLayers,function(b){a.map.removeLayer(b)});this._currentVectorLayers=[];this._wmsLayers=[];this.requestData!==null&&
this.requestData.abort();this.requestData=e.ajax({url:Neatline.dataSources.map,dataType:"json",success:function(b){a._buildLayers(b);a._addClickControls();a._currentEditItem!==null&&a.edit(a._currentEditItem,!0)}})},_buildLayers:function(a){var b=this;this._db=TAFFY();_.each(a,function(a){var d=[],d=(new OpenLayers.Format.KML).read(a.wkt);_.isEmpty(d)&&(_.isNull(a.wkt)||e.each(a.wkt.split(b.options.wkt_delimiter),function(a,b){var c=new OpenLayers.Format.WKT;_.isUndefined(c.read(b))||(c=new OpenLayers.Geometry.fromWKT(b),
c=new OpenLayers.Feature.Vector(c),d.push(c))}));a.vector_opacity/=100;a.stroke_opacity/=100;a.select_opacity/=100;a.graphic_opacity/=100;var f=b._getStyleMap(a.vector_color,a.vector_opacity,a.stroke_color,a.stroke_opacity,a.stroke_width,a.point_radius,a.point_image,a.highlight_color,a.select_opacity,a.graphic_opacity),f=new OpenLayers.Layer.Vector(a.title,{styleMap:f,displayInLayerSwitcher:!1});f.addFeatures(d);f.setMap(b.map);var g=null;if(!_.isNull(a.wmsAddress)&&!_.isNull(a.layers))g=new OpenLayers.Layer.WMS(a.title,
a.wmsAddress,{layers:a.layers,styles:"",transparent:!0,format:"image/png8",tiled:!1},{buffer:0,displayOutsideMaxExtent:!0,isBaseLayer:!1}),g.opacity=a.vector_opacity,b._wmsLayers.push(g),b.map.addLayer(g);b._db.insert({itemid:a.item_id,layerid:f.id,recordid:a.id,slug:a.slug,data:a,layer:f,wms:g,selected:!1});b._currentVectorLayers.push(f);b.map.addLayer(f)});this.renderVisibility(this.now)},_addClickControls:function(){var a=this;this._removeSelectControls();this.highlightControl=new OpenLayers.Control.SelectFeature(this._currentVectorLayers,
{hover:!0,highlightOnly:!0,renderIntent:"select",overFeature:function(b){var c=a._db({layerid:b.layer.id}).first();a._trigger("featureenter",{},{record:c});c.selected||_.each(c.layer.features,function(b){a.highlightControl.highlight(b)});a._hoveredRecord=c;a._hoveredFeature=b},outFeature:function(b){b=a._db({layerid:b.layer.id}).first();a._trigger("featureleave",{},{record:b});b.selected||_.each(b.layer.features,function(b){a.highlightControl.unhighlight(b)});a._hoveredRecord=null;a._hoveredFeature=
null}});this.clickControl=new OpenLayers.Control.SelectFeature(this._currentVectorLayers,{clickout:!0,toggle:!0,onSelect:function(b){var c=a._db({layerid:b.layer.id}).first();a._clickedFeature=b;a._selectedRecord=c;c.selected=!0;a._trigger("featureclick",{},{recordid:c.recordid,slug:c.data.slug});_.isUndefined(a.modifyFeatures)||a.modifyFeatures.selectFeature(a._clickedFeature)},onUnselect:function(b){var c=a._db({layerid:b.layer.id}).first();a._clickedFeature=null;c.selected=!1;a.unselectVectors(c.id);
_.isUndefined(a.modifyFeatures)||a.modifyFeatures.unselectFeature(b);a._trigger("featureunselect",i,{feature:b,record:c})}});this.highlightControl.handlers.feature.stopDown=!1;this.clickControl.handlers.feature.stopDown=!1;this.map.addControl(this.highlightControl);this.highlightControl.activate();this.map.addControl(this.clickControl);this.clickControl.activate()},_removeSelectControls:function(){_.isUndefined(this.clickControl)||(this.map.removeControl(this.clickControl),this.clickControl.destroy(),
delete this.clickControl);_.isUndefined(this.highlightControl)||(this.map.removeControl(this.highlightControl),this.highlightControl.destroy(),delete this.highlightControl)},_removeEditControls:function(){_.isUndefined(this.editToolbar)||(this.map.removeControl(this.editToolbar),this.editToolbar.destroy(),delete this.editToolbar);_.isUndefined(this.modifyFeatures)||(this.map.removeControl(this.modifyFeatures),this.modifyFeatures.destroy(),delete this.modifyFeatures)},_setStartingVisibility:function(){Neatline.record.default_focus_date?
this.renderVisibility(Neatline.record.default_focus_date):this.renderVisibility(Date.now())},zoomToItemVectors:function(a){this._selectRecord(this._db({recordid:parseInt(a,10)}).first())},zoomToItemVectorsBySlug:function(a){this._selectRecord(this._db({slug:a}).first())},renderVisibility:function(a){this.now=moment(a);this._db().each(_.bind(function(a){var c=moment(a.data.start_visible_date),d=moment(a.data.end_visible_date);!_.isNull(c)&&!_.isNull(d)?(c=this.now>c&&this.now<d,a.layer.setVisibility(c),
a.wms&&a.wms.setVisibility(c)):!_.isNull(c)&&_.isNull(d)?(c=this.now>c,a.layer.setVisibility(c),a.wms&&a.wms.setVisibility(c)):_.isNull(c)&&!_.isNull(d)&&(c=this.now<d,a.layer.setVisibility(c),a.wms&&a.wms.setVisibility(c))},this))},_selectRecord:function(a){if(a&&!this.setViewport(a.data.bounds||a.data.center,a.data.zoom)){var b=a.layer.getDataExtent();_.isNaN(b.top)||this.map.zoomToExtent(a.layer.getDataExtent())}a&&_.isNull(a.wms);a.selected=!0;this._selectedRecord=a},_resetWmsZIndices:function(){_.each(this._wmsLayers,
function(a){a.setZIndex(0)})},_getStyleMap:function(a,b,c,d,f,g,e,h,i,j){return new OpenLayers.StyleMap({"default":new OpenLayers.Style({fillColor:a,fillOpacity:b,strokeColor:c,strokeOpacity:d,pointRadius:g,externalGraphic:e,strokeWidth:f,graphicOpacity:j}),select:new OpenLayers.Style({fillColor:h,fillOpacity:i,strokeColor:h,strokeOpacity:d,pointRadius:g,externalGraphic:e,strokeWidth:f,graphicOpacity:j}),temporary:new OpenLayers.Style({fillColor:h,fillOpacity:b,strokeColor:h,strokeOpacity:d,pointRadius:g,
externalGraphic:e,strokeWidth:f,graphicOpacity:j})})},_getBaseLayers:function(){this.osm=new OpenLayers.Layer.OSM;this.gphy=new OpenLayers.Layer.Google("Google Physical",{type:google.maps.MapTypeId.TERRAIN});this.gmap=new OpenLayers.Layer.Google("Google Streets",{numZoomLevels:20});this.ghyb=new OpenLayers.Layer.Google("Google Hybrid",{type:google.maps.MapTypeId.HYBRID,numZoomLevels:20});this.gsat=new OpenLayers.Layer.Google("Google Satellite",{type:google.maps.MapTypeId.SATELLITE,numZoomLevels:22});
this.stwc=new OpenLayers.Layer.Stamen("Stamen Watercolor",{provider:"watercolor",tileOptions:{crossOriginKeyword:null}});this.sttn=new OpenLayers.Layer.Stamen("Stamen Toner",{provider:"toner",tileOptions:{crossOriginKeyword:null}});this.sttr=new OpenLayers.Layer.Stamen("Stamen Terrain",{provider:"terrain",tileOptions:{crossOriginKeyword:null}});return[this.osm,this.gphy,this.gmap,this.ghyb,this.gsat,this.stwc,this.sttn,this.sttr]},_setDefaultLayer:function(){switch(Neatline.baseLayer.name){case "OpenStreetMap":this.map.setBaseLayer(this.osm);
break;case "Google Physical":this.map.setBaseLayer(this.gphy);break;case "Google Streets":this.map.setBaseLayer(this.gmap);break;case "Google Hybrid":this.map.setBaseLayer(this.ghyb);break;case "Google Satellite":this.map.setBaseLayer(this.gsat);break;case "Stamen Watercolor":this.map.setBaseLayer(this.stwc);break;case "Stamen Toner":this.map.setBaseLayer(this.sttn);break;case "Stamen Terrain":this.map.setBaseLayer(this.sttr)}},selectVectors:function(a){this._renderVectorSelect(this._db({recordid:parseInt(a,
10)}).first())},_renderVectorSelect:function(a){var b=this;a&&!_.isUndefined(a.data)&&(e.each(a.layer.features,function(a,d){b.highlightControl.select(d)}),_.isNull(a.wms)||a.wms.setOpacity(a.data.select_opacity))},unselectSelectedRecord:function(){this._removeVectorSelect(this._selectedRecord)},unselectVectors:function(a){this._removeVectorSelect(this._db({recordid:parseInt(a,10)}).first())},_removeVectorSelect:function(a){var b=this;if(a&&!_.isUndefined(a.data))e.each(a.layer.features,function(a,
d){b.highlightControl.unselect(d)}),_.isNull(a.wms)||a.wms.setOpacity(a.data.vector_opacity),a.selected=!1},highlightVectors:function(a){this._renderVectorHighlight(this._db({recordid:parseInt(a,10)}).first())},highlightVectorsBySlug:function(a){this._renderVectorHighlight(this._db({slug:a}).first())},_renderVectorHighlight:function(a){var b=this;a&&!_.isUndefined(a.data)&&e.each(a.layer.features,function(a,d){b.highlightControl.highlight(d)})},unhighlightHoveredRecord:function(){this._removeVectorHighlight(this._hoveredRecord)},
unhighlightVectors:function(a){this._removeVectorHighlight(this._db({recordid:parseInt(a,10)}).first())},unhighlightVectorsBySlug:function(a){this._removeVectorHighlight(this._db({slug:a}).first())},_removeVectorHighlight:function(a){var b=this;!_.isUndefined(a.data)&&!a.selected&&e.each(a.layer.features,function(a,d){b.highlightControl.unhighlight(d)})},refresh:function(a){this.map.updateSize();this.positionControls(a.top,a.left,a.width,a.height)},setViewport:function(a,b){var c=!1;if(!_.isNull(a)){var d=
a.split(",");d.length===4?(this.map.zoomToExtent(new OpenLayers.Bounds(parseFloat(d[0]),parseFloat(d[1]),parseFloat(d[2]),parseFloat(d[3]))),c=!0):d.length===2&&(b=_.isNull(b)?5:parseInt(b,10),this.map.setCenter(new OpenLayers.LonLat(parseFloat(d[0].trim()),parseFloat(d[1].trim())),b),c=!0)}return c}})})(jQuery);
