/*
     http://www.apache.org/licenses/LICENSE-2.0.html Apache 2 License
*/
(function(e,f){e.widget("neatline.neatlinetimeline",{_create:function(){this._window=e(window);this.zoomContainer=e("#zoom-buttons");this.zoomIn=this.zoomContainer.find(".zoom-in");this.zoomOut=this.zoomContainer.find(".zoom-out");this._idToTapeElements={};this._zoomSteps=this.getZoomIndexArray();this._currentZoomStep=Neatline.timelineZoom;this._currentDate=null;this._instantiateSimile();this._constructZoomButtons();this.element.disableSelection()},_instantiateSimile:function(a){this.zoomContainer.detach();
this.eventSource=new Timeline.DefaultEventSource;var b=this._zoomSteps[this._currentZoomStep],c=b.unit,b=b.pixelsPerInterval,d=Timeline.ClassicTheme.create();d.event.track.height=15;d.event.tape.height=10;var e=100;Neatline.timeline.isContextBand===1&&(e-=Neatline.timeline.contextBandHeight);this.bandInfos=[Timeline.createBandInfo({eventSource:this.eventSource,width:e+"%",intervalUnit:c,intervalPixels:b,zoomIndex:this._currentZoomStep,zoomSteps:this._zoomSteps,theme:d,timeZone:SimileAjax.DateTime.getTimezone()})];
if(Neatline.timeline.isContextBand===1)c=Neatline.timeline.contextBandUnit.toUpperCase(),this.bandInfos.push(Timeline.createBandInfo({overview:!0,eventSource:this.eventSource,width:Neatline.timeline.contextBandHeight+"%",intervalUnit:Timeline.DateTime[c],intervalPixels:300})),this.bandInfos[1].syncWith=0,this.bandInfos[1].highlight=!0;c=document.getElementById("timeline");this.timeline=Timeline.create(c,this.bandInfos);this.loadData();a||(this._catchClickCallback(),this._catchZoomCallback());this.timeline.getBand(0).addOnScrollListener(_.bind(function(){var a=
this.timeline.getBand(0).getCenterVisibleDate();this._trigger("scroll",{},{date:a});this._currentDate=a},this))},_constructZoomButtons:function(){var a=this;this.element.append(this.zoomContainer);this.zoomIn.bind("mousedown",function(){if(a._currentZoomStep>0){var b=a._getCenterOffset();a.timeline.getBand(0).zoom(!0,b.x,b.y)}a.refresh()});this.zoomOut.bind("mousedown",function(){if(a._currentZoomStep<a._zoomSteps.length-1){var b=a._getCenterOffset();a.timeline.getBand(0).zoom(!1,b.x,b.y)}a.refresh()})},
_catchClickCallback:function(){var a=this;Timeline.OriginalEventPainter.prototype._showBubble=function(b,c,d){a._trigger("eventclick",{},{recordid:d._eventID,slug:d._obj.slug})}},_catchZoomCallback:function(){var a=this;Timeline._Band.prototype.zoom=function(b,c){if(this._zoomSteps){c+=this._viewOffset;var d=this._ether.pixelOffsetToDate(c);this._etherPainter.zoom(this._ether.zoom(b));this._moveEther(Math.round(-this._ether.dateToPixelOffset(d)));this._moveEther(c);b?a._incrementZoomStepDown():a._incrementZoomStepUp()}}},
loadData:function(){var a;this.timeline.loadJSON(Neatline.dataSources.timeline,_.bind(function(a,c){this.eventSource.clear();this.eventSource.loadJSON(a,c)},this));_.isNull(this._currentDate)?Neatline.default_focus_date!==null&&(a=Date.parse(Neatline.record.default_focus_date),this.timeline.getBand(0).setCenterVisibleDate(a)):(a=this._currentDate,this.timeline.getBand(0).setCenterVisibleDate(a));this.timeline.getBand(0).getEventPainter().addEventPaintListener(_.bind(function(a,c,d,e){e!==null&&(this._buildSpanStyler(d,
e),this._listenForHover(d,e))},this))},_buildSpanStyler:function(a,b){var c=e(b[0]);c.data("positioningStyles",c.attr("style"));c.spanstyler();c.spanstyler("constructCss",a._obj.color,a._obj.left_ambiguity,a._obj.right_ambiguity);c.spanstyler("applyCss");this._idToTapeElements[a._eventID]=[c]},_listenForHover:function(a,b){_.each(b,_.bind(function(c){e(c).bind({mouseenter:_.bind(function(){this._trigger("evententer",{},{id:a._eventID,title:a._text,description:a._description,show_bubble:a._obj.show_bubble})},
this),mouseleave:_.bind(function(){this._trigger("eventleave",{},{id:a._eventID,title:a._text,description:a._description,show_bubble:a._obj.show_bubble})},this)})},this))},_getCenterOffset:function(){var a=this.timeline.getBand(0)._div;return{x:-parseInt(e(a).css("left"),10)+this.element.width()/2,y:-parseInt(e(a).css("top"),10)+this.element.height()/2}},zoomToEvent:function(a){var b=this;e.each(this.timeline._bands[0]._eventSource._events._idToEvent,function(c,d){d._eventID===parseInt(a,10)&&b.timeline.getBand(0).setCenterVisibleDate(d._start)})},
zoomToEventBySlug:function(a){var b=this;e.each(this.timeline._bands[0]._eventSource._events._idToEvent,function(c,d){d._obj.slug===a&&b.timeline.getBand(0).setCenterVisibleDate(d._start)})},getCenterForSave:function(){return this.timeline.getBand(0).getCenterVisibleDate().toString()},getZoomForSave:function(){return this._currentZoomStep},setDateAmbiguity:function(a,b,c,d){typeof this._idToTapeElements[a]!=="undefined"&&e.each(this._idToTapeElements[a],function(a,e){e.attr("style",e.data("positioningStyles"));
e.spanstyler("constructCss",b,c,d);e.spanstyler("applyCss")})},setDateColor:function(a,b){typeof this._idToTapeElements[a]!=="undefined"&&e.each(this._idToTapeElements[a],function(a,d){d.attr("style",d.data("positioningStyles"));d.spanstyler("constructCss",b,null,null);d.spanstyler("applyCss")})},renderDefaults:function(a,b,c){Neatline.record.is_context_band=c;Neatline.record.default_context_band_height=a;Neatline.record.default_context_band_unit=b;Neatline.timeline.isContextBand=c;Neatline.timeline.contextBandUnit=
b;Neatline.timeline.contextBandHeight=a;this.reinstantiate()},getZoomIndexArray:function(){return[{pixelsPerInterval:300,unit:Timeline.DateTime.HOUR},{pixelsPerInterval:200,unit:Timeline.DateTime.HOUR},{pixelsPerInterval:100,unit:Timeline.DateTime.HOUR},{pixelsPerInterval:50,unit:Timeline.DateTime.HOUR},{pixelsPerInterval:300,unit:Timeline.DateTime.DAY},{pixelsPerInterval:200,unit:Timeline.DateTime.DAY},{pixelsPerInterval:100,unit:Timeline.DateTime.DAY},{pixelsPerInterval:50,unit:Timeline.DateTime.DAY},
{pixelsPerInterval:300,unit:Timeline.DateTime.WEEK},{pixelsPerInterval:200,unit:Timeline.DateTime.WEEK},{pixelsPerInterval:100,unit:Timeline.DateTime.WEEK},{pixelsPerInterval:50,unit:Timeline.DateTime.WEEK},{pixelsPerInterval:300,unit:Timeline.DateTime.MONTH},{pixelsPerInterval:200,unit:Timeline.DateTime.MONTH},{pixelsPerInterval:100,unit:Timeline.DateTime.MONTH},{pixelsPerInterval:50,unit:Timeline.DateTime.MONTH},{pixelsPerInterval:300,unit:Timeline.DateTime.YEAR},{pixelsPerInterval:200,unit:Timeline.DateTime.YEAR},
{pixelsPerInterval:100,unit:Timeline.DateTime.YEAR},{pixelsPerInterval:50,unit:Timeline.DateTime.YEAR},{pixelsPerInterval:300,unit:Timeline.DateTime.DECADE},{pixelsPerInterval:200,unit:Timeline.DateTime.DECADE},{pixelsPerInterval:100,unit:Timeline.DateTime.DECADE},{pixelsPerInterval:50,unit:Timeline.DateTime.DECADE},{pixelsPerInterval:300,unit:Timeline.DateTime.CENTURY},{pixelsPerInterval:200,unit:Timeline.DateTime.CENTURY},{pixelsPerInterval:100,unit:Timeline.DateTime.CENTURY},{pixelsPerInterval:50,
unit:Timeline.DateTime.CENTURY}]},_incrementZoomStepUp:function(){this._currentZoomStep<this._zoomSteps.length-1&&this._currentZoomStep++},_incrementZoomStepDown:function(){this._currentZoomStep>0&&this._currentZoomStep--},reinstantiate:function(){this.timeline.dispose();this.timeline=f;this._instantiateSimile();this._constructZoomButtons();this.element.disableSelection()},refresh:function(){this.timeline.layout()},getAttr:function(a){return this[a]}})})(jQuery);
