/*
     http://www.apache.org/licenses/LICENSE-2.0.html Apache 2 License
*/
(function(f){f.widget("neatline.gradientbuilder",{options:{css:{width_offset:5}},_create:function(){this._window=f(window);this.editor=this.element.find(".date-ambiguity-editor");this.leftMarker=this.element.find(".stop-marker.left");this.rightMarker=this.element.find(".stop-marker.right");this.swatches=this.element.find(".color-swatch");this.leftPercentInput=this.element.find('input[name="left-ambiguity-percentage"]');this.rightPercentInput=this.element.find('input[name="right-ambiguity-percentage"]');
this.leftPercent=parseInt(this.leftPercentInput.val());this.rightPercent=parseInt(this.rightPercentInput.val());this.getDimensions();this.positionMarkers(this.leftPercent,this.rightPercent);this.editor.spanstyler();this._addEvents()},getDimensions:function(){this.editorWidth=this.editor.width();this.editorHeight=this.editor.height();this.editorOffset=this.editor.offset()},positionMarkers:function(b,a){var c=this.editorWidth-this.editorWidth*(a/100);this.leftMarker.css({left:this.editorWidth*(b/100)-
this.options.css.width_offset,top:this.editorHeight});this.rightMarker.css({right:c-this.options.css.width_offset,top:this.editorHeight});this.leftPercent=b;this.leftPercentInput.val(b);this.rightPercent=a;this.rightPercentInput.val(a)},setColor:function(b){this.color=b;this.editor.spanstyler("constructCss",b,this.leftPercent,this.rightPercent);this.editor.spanstyler("applyCss");this.swatches.css("background",b)},refresh:function(){this.getDimensions();this.positionMarkers(this.leftPercent,this.rightPercent);
this.setColor(this.color)},_addEvents:function(){var b=this;this.leftMarker.bind({mousedown:function(a){b._doLeftDrag(a)}});this.rightMarker.bind({mousedown:function(a){b._doRightDrag(a)}})},_doLeftDrag:function(b){var a=this,c=b.pageX,e=this.__pxToInt(this.leftMarker.css("left"));this._window.bind({mousemove:function(b){var b=e+(b.pageX-c),d=a._leftPercentFromOffset(b);b+a.options.css.width_offset>=0&&d<a.rightPercent-5?a.leftMarker.css("left",b):d>=a.rightPercent-5?b=(a.rightPercent-5)/100*a.editorWidth:
(b=-a.options.css.width_offset,a.leftMarker.css("left",b));a.leftPercent=a._leftPercentFromOffset(b);a.leftPercentInput.val(a.leftPercent);a.editor.spanstyler("constructCss",a.color,a.leftPercent,a.rightPercent);a.editor.spanstyler("applyCss");a._trigger("stopHandleDrag",{},{color:a.color,leftPercent:a.leftPercent,rightPercent:a.rightPercent})},mouseup:function(){a._window.unbind("mousemove mouseup")}})},_doRightDrag:function(b){var a=this,c=b.pageX,e=this.__pxToInt(this.rightMarker.css("right"));
this._window.bind({mousemove:function(b){var b=e-(b.pageX-c),d=a._rightPercentFromOffset(b);b+a.options.css.width_offset>=0&&d>a.leftPercent+5||(b=d<=a.leftPercent+5?a.editorWidth-(a.leftPercent+5)/100*a.editorWidth:-a.options.css.width_offset);a.rightMarker.css("right",b);a.rightPercent=a._rightPercentFromOffset(b);a.rightPercentInput.val(a.rightPercent);a.editor.spanstyler("constructCss",a.color,a.leftPercent,a.rightPercent);a.editor.spanstyler("applyCss");a._trigger("stopHandleDrag",{},{color:a.color,
leftPercent:a.leftPercent,rightPercent:a.rightPercent})},mouseup:function(){a._window.unbind("mousemove mouseup")}})},_leftPercentFromOffset:function(b){return Math.round((b+this.options.css.width_offset)/this.editorWidth*100)},_rightPercentFromOffset:function(b){return Math.round((this.editorWidth-b-this.options.css.width_offset)/this.editorWidth*100)},__pxToInt:function(b){var a=b.indexOf("px");return parseInt(b.slice(0,a))}})})(jQuery);
