(function(g,h){function q(b,a){if(b.attributes.length!=a.attributes.length)return!1;for(var c=0,d=b.attributes.length,e,f;c<d;++c)if(e=b.attributes[c],f=e.name,f!="class"){f=a.attributes.getNamedItem(f);if(e.specified!=f.specified)return!1;if(e.specified&&e.nodeValue!==f.nodeValue)return!1}return!0}function k(b,a){return h.dom.isCharacterDataNode(b)?a==0?!!b.previousSibling:a==b.length?!!b.nextSibling:!0:a>0&&a<b.childNodes.length}function j(b,a,c){var d;if(h.dom.isCharacterDataNode(a))c==0?(c=h.dom.getNodeIndex(a),
a=a.parentNode):c==a.length?(c=h.dom.getNodeIndex(a)+1,a=a.parentNode):d=h.dom.splitDataNode(a,c);if(!d){d=a.cloneNode(!1);d.id&&d.removeAttribute("id");for(var e;e=a.childNodes[c];)d.appendChild(e);h.dom.insertAfter(d,a)}return a==b?d:j(b,d.parentNode,h.dom.getNodeIndex(d))}function n(b){this.firstTextNode=(this.isElementMerge=b.nodeType==g.ELEMENT_NODE)?b.lastChild:b;this.textNodes=[this.firstTextNode]}function l(b,a,c,d){this.tagNames=b||[r];this.cssClass=a||"";this.similarClassRegExp=c;this.normalize=
d;this.applyToAnyTagName=!1}var r="span",p=/\s+/g;n.prototype={doMerge:function(){for(var b=[],a,c,d=0,e=this.textNodes.length;d<e;++d)a=this.textNodes[d],c=a.parentNode,b[d]=a.data,d&&(c.removeChild(a),c.hasChildNodes()||c.parentNode.removeChild(c));return this.firstTextNode.data=b=b.join("")},getLength:function(){for(var b=this.textNodes.length,a=0;b--;)a+=this.textNodes[b].length;return a},toString:function(){for(var b=[],a=0,c=this.textNodes.length;a<c;++a)b[a]="'"+this.textNodes[a].data+"'";
return"[Merge("+b.join(",")+")]"}};l.prototype={getAncestorWithClass:function(b){for(var a;b;){if(this.cssClass)if(a=this.cssClass,b.className){var c=b.className.match(this.similarClassRegExp)||[];a=c[c.length-1]===a}else a=!1;else a=!0;if(b.nodeType==g.ELEMENT_NODE&&h.dom.arrayContains(this.tagNames,b.tagName.toLowerCase())&&a)return b;b=b.parentNode}return!1},postApply:function(b,a){for(var c=b[0],d=b[b.length-1],e=[],f,g=c,h=d,j=0,k=d.length,m,l,i=0,o=b.length;i<o;++i)if(m=b[i],l=this.getAdjacentMergeableTextNode(m.parentNode,
!1)){f||(f=new n(l),e.push(f));f.textNodes.push(m);if(m===c)g=f.firstTextNode,j=g.length;if(m===d)h=f.firstTextNode,k=f.getLength()}else f=null;if(c=this.getAdjacentMergeableTextNode(d.parentNode,!0))f||(f=new n(d),e.push(f)),f.textNodes.push(c);if(e.length){for(i=0,o=e.length;i<o;++i)e[i].doMerge();a.setStart(g,j);a.setEnd(h,k)}},getAdjacentMergeableTextNode:function(b,a){var c=b.nodeType==g.TEXT_NODE,d=c?b.parentNode:b,e=a?"nextSibling":"previousSibling";if(c){if((c=b[e])&&c.nodeType==g.TEXT_NODE)return c}else if((c=
d[e])&&this.areElementsMergeable(b,c))return c[a?"firstChild":"lastChild"];return null},areElementsMergeable:function(b,a){return h.dom.arrayContains(this.tagNames,(b.tagName||"").toLowerCase())&&h.dom.arrayContains(this.tagNames,(a.tagName||"").toLowerCase())&&b.className.replace(p," ")==a.className.replace(p," ")&&q(b,a)},createContainer:function(b){b=b.createElement(this.tagNames[0]);if(this.cssClass)b.className=this.cssClass;return b},applyToTextNode:function(b){var a=b.parentNode;if(a.childNodes.length==
1&&h.dom.arrayContains(this.tagNames,a.tagName.toLowerCase())){if(this.cssClass)if(b=this.cssClass,a.className){if(a.className)a.className=a.className.replace(this.similarClassRegExp,"");a.className+=" "+b}else a.className=b}else a=this.createContainer(h.dom.getDocument(b)),b.parentNode.insertBefore(a,b),a.appendChild(b)},isRemovable:function(b){return h.dom.arrayContains(this.tagNames,b.tagName.toLowerCase())&&g.lang.string(b.className).trim()==this.cssClass},undoToTextNode:function(b,a,c){a.containsNode(c)||
(b=a.cloneRange(),b.selectNode(c),b.isPointInRange(a.endContainer,a.endOffset)&&k(a.endContainer,a.endOffset)&&(j(c,a.endContainer,a.endOffset),a.setEndAfter(c)),b.isPointInRange(a.startContainer,a.startOffset)&&k(a.startContainer,a.startOffset)&&(c=j(c,a.startContainer,a.startOffset)));if(this.similarClassRegExp&&c.className)c.className=c.className.replace(this.similarClassRegExp,"");if(this.isRemovable(c)){a=c;for(c=a.parentNode;a.firstChild;)c.insertBefore(a.firstChild,a);c.removeChild(a)}},applyToRange:function(b){var a=
b.getNodes([g.TEXT_NODE]);if(!a.length)try{var c=this.createContainer(b.endContainer.ownerDocument);b.surroundContents(c);this.selectNode(b,c);return}catch(d){}b.splitBoundaries();a=b.getNodes([g.TEXT_NODE]);if(a.length){for(var e=0,f=a.length;e<f;++e)c=a[e],this.getAncestorWithClass(c)||this.applyToTextNode(c);b.setStart(a[0],0);c=a[a.length-1];b.setEnd(c,c.length);this.normalize&&this.postApply(a,b)}},undoToRange:function(b){var a=b.getNodes([g.TEXT_NODE]),c,d;a.length?(b.splitBoundaries(),a=b.getNodes([g.TEXT_NODE])):
(a=b.endContainer.ownerDocument.createTextNode(g.INVISIBLE_SPACE),b.insertNode(a),b.selectNode(a),a=[a]);for(var e=0,f=a.length;e<f;++e)c=a[e],(d=this.getAncestorWithClass(c))&&this.undoToTextNode(c,b,d);f==1?this.selectNode(b,a[0]):(b.setStart(a[0],0),c=a[a.length-1],b.setEnd(c,c.length),this.normalize&&this.postApply(a,b))},selectNode:function(b,a){var c=a.nodeType===g.ELEMENT_NODE,d="canHaveHTML"in a?a.canHaveHTML:!0,e=c?a.innerHTML:a.data;if((e=e===""||e===g.INVISIBLE_SPACE)&&c&&d)try{a.innerHTML=
g.INVISIBLE_SPACE}catch(f){}b.selectNodeContents(a);e&&c?b.collapse(!1):e&&(b.setStartAfter(a),b.setEndAfter(a))},getTextSelectedByRange:function(b,a){var c=a.cloneRange();c.selectNodeContents(b);var d=c.intersection(a),d=d?d.toString():"";c.detach();return d},isAppliedToRange:function(b){var a=[],c,d=b.getNodes([g.TEXT_NODE]);if(!d.length)return(c=this.getAncestorWithClass(b.startContainer))?[c]:!1;for(var e=0,f=d.length,h;e<f;++e)if(h=this.getTextSelectedByRange(d[e],b),c=this.getAncestorWithClass(d[e]),
h!=""&&!c)return!1;else a.push(c);return a},toggleRange:function(b){this.isAppliedToRange(b)?this.undoToRange(b):this.applyToRange(b)}};g.selection.HTMLApplier=l})(wysihtml5,rangy);
