(function(c){var b=c.dom,e=c.browser;c.views.Composer=c.views.View.extend({name:"composer",CARET_HACK:"<br>",constructor:function(d,a,b){this.base(d,a,b);this.textarea=this.parent.textarea;this._initSandbox()},clear:function(){this.element.innerHTML=e.displaysCaretInEmptyContentEditableCorrectly()?"":this.CARET_HACK},getValue:function(d){var a=this.isEmpty()?"":c.quirks.getCorrectInnerHTML(this.element);d&&(a=this.parent.parse(a));return a=c.lang.string(a).replace(c.INVISIBLE_SPACE).by("")},setValue:function(d,
a){a&&(d=this.parent.parse(d));this.element.innerHTML=d},show:function(){this.iframe.style.display=this._displayStyle||"";this.disable();this.enable()},hide:function(){this._displayStyle=b.getStyle("display").from(this.iframe);if(this._displayStyle==="none")this._displayStyle=null;this.iframe.style.display="none"},disable:function(){this.element.removeAttribute("contentEditable");this.base()},enable:function(){this.element.setAttribute("contentEditable","true");this.base()},focus:function(d){c.browser.doesAsyncFocus()&&
this.hasPlaceholderSet()&&this.clear();this.base();var a=this.element.lastChild;d&&a&&(a.nodeName==="BR"?this.selection.setBefore(this.element.lastChild):this.selection.setAfter(this.element.lastChild))},getTextContent:function(){return b.getTextContent(this.element)},hasPlaceholderSet:function(){return this.getTextContent()==this.textarea.element.getAttribute("placeholder")},isEmpty:function(){var d=this.element.innerHTML;return d===""||d===this.CARET_HACK||this.hasPlaceholderSet()||this.getTextContent()===
""&&!this.element.querySelector("blockquote, ul, ol, img, embed, object, table, iframe, svg, video, audio, button, input, select, textarea")},_initSandbox:function(){var d=this;this.sandbox=new b.Sandbox(function(){d._create()},{stylesheets:this.config.stylesheets});this.iframe=this.sandbox.getIframe();var a=document.createElement("input");a.type="hidden";a.name="_wysihtml5_mode";a.value=1;var c=this.textarea.element;b.insert(this.iframe).after(c);b.insert(a).after(c)},_create:function(){var d=this;
this.doc=this.sandbox.getDocument();this.element=this.doc.body;this.textarea=this.parent.textarea;this.element.innerHTML=this.textarea.getValue(!0);this.enable();this.selection=new c.Selection(this.parent);this.commands=new c.Commands(this.parent);b.copyAttributes("className,spellcheck,title,lang,dir,accessKey".split(",")).from(this.textarea.element).to(this.element);b.addClass(this.element,this.config.composerClassName);this.config.style&&this.style();this.observe();var a=this.config.name;a&&(b.addClass(this.element,
a),b.addClass(this.iframe,a));(a=typeof this.config.placeholder==="string"?this.config.placeholder:this.textarea.element.getAttribute("placeholder"))&&b.simulatePlaceholder(this.parent,this,a);this.commands.exec("styleWithCSS",!1);this._initAutoLinking();this._initObjectResizing();this._initUndoManager();(this.textarea.element.hasAttribute("autofocus")||document.querySelector(":focus")==this.textarea.element)&&setTimeout(function(){d.focus()},100);c.quirks.insertLineBreakOnReturn(this);e.clearsContentEditableCorrectly()||
c.quirks.ensureProperClearing(this);e.clearsListsInContentEditableCorrectly()||c.quirks.ensureProperClearingOfLists(this);this.initSync&&this.config.sync&&this.initSync();this.textarea.hide();this.parent.fire("beforeload").fire("load")},_initAutoLinking:function(){var d=this,a=e.canDisableAutoLinking(),f=e.doesAutoLinkingInContentEditable();a&&this.commands.exec("autoUrlDetect",!1);if(this.config.autoLink){(!f||f&&a)&&this.parent.observe("newword:composer",function(){d.selection.executeAndRestore(function(a,
d){b.autoLink(d.parentNode)})});var i=this.sandbox.getDocument().getElementsByTagName("a"),j=b.autoLink.URL_REG_EXP,g=function(a){a=c.lang.string(b.getTextContent(a)).trim();a.substr(0,4)==="www."&&(a="http://"+a);return a};b.observe(this.element,"keydown",function(a){if(i.length){var a=d.selection.getSelectedNode(a.target.ownerDocument),c=b.getParentElement(a,{nodeName:"A"},4),e;c&&(e=g(c),setTimeout(function(){var a=g(c);a!==e&&a.match(j)&&c.setAttribute("href",a)},0))}})}},_initObjectResizing:function(){var d=
["width","height"],a=d.length,f=this.element;this.commands.exec("enableObjectResizing",this.config.allowObjectResizing);this.config.allowObjectResizing?e.supportsEvent("resizeend")&&b.observe(f,"resizeend",function(b){for(var b=b.target||b.srcElement,e=b.style,g=0,h;g<a;g++)h=d[g],e[h]&&(b.setAttribute(h,parseInt(e[h],10)),e[h]="");c.quirks.redraw(f)}):e.supportsEvent("resizestart")&&b.observe(f,"resizestart",function(a){a.preventDefault()})},_initUndoManager:function(){new c.UndoManager(this.parent)}})})(wysihtml5);
